import { CityProfile } from './types';

// ─── Europe City Data ─────────────────────────────────

export const EUROPE_CITIES: CityProfile[] = [
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // PARIS (巴黎)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'paris',
    name: '파리',
    nameLocal: 'Paris',
    country: '프랑스',
    region: '서유럽',
    description: '에펠탑, 루브르, 노트르담. 예술과 낭만, 미식의 도시.',
    character: '예술과 낭만이 숨 쉬는 빛의 도시',
    bestSeasons: ['spring', 'autumn'],
    averageStay: '4~6일',
    budgetPerDay: { economy: '100,000~180,000원', mid: '250,000~400,000원', premium: '500,000원~' },
    areas: [
      {
        name: '에펠탑·샹드마르스',
        nameLocal: 'Tour Eiffel & Champ de Mars',
        description: '파리의 상징 에펠탑과 주변 공원. 센 강변 산책도.',
        walkable: true,
        timeNeeded: '2~3시간',
        places: [
          {
            name: '에펠탑',
            nameLocal: 'Tour Eiffel',
            category: '관광지',
            description: '1889년 건설된 파리의 상징. 전망대에서 파리 전경 감상.',
            mustVisit: true,
            hours: '09:30~23:45',
            admission: '€26.80 (정상)',
            duration: '2시간',
            latitude: 48.8584,
            longitude: 2.2945,
            rating: 4.6,
            tips: '온라인 사전 예약 필수. 트로카데로 광장에서 보는 에펠탑이 포토 스팟.',
          },
          {
            name: '센 강 크루즈',
            nameLocal: 'Croisière sur la Seine',
            category: '체험',
            description: '바토무슈 등 유람선으로 파리 주요 명소를 수상에서 감상.',
            mustVisit: true,
            hours: '10:00~22:30',
            admission: '€15~',
            duration: '1시간',
            latitude: 48.8613,
            longitude: 2.2985,
            rating: 4.5,
          },
        ],
      },
      {
        name: '루브르·튈르리',
        nameLocal: 'Louvre & Tuileries',
        description: '세계 최대 미술관 루브르와 콩코르드 광장까지 이어지는 정원.',
        walkable: true,
        timeNeeded: '반나절',
        places: [
          {
            name: '루브르 박물관',
            nameLocal: 'Musée du Louvre',
            category: '관광지',
            description: '모나리자, 밀로의 비너스 등 38만 점 이상 소장. 세계 최고의 미술관.',
            mustVisit: true,
            hours: '09:00~18:00 (수·금 ~21:45)',
            closedDay: '화요일',
            admission: '€22',
            duration: '3~4시간',
            latitude: 48.8606,
            longitude: 2.3376,
            rating: 4.7,
            tips: '수·금 야간개장 때 방문하면 인파가 적어요.',
          },
          {
            name: '오르세 미술관',
            nameLocal: 'Musée d\'Orsay',
            category: '관광지',
            description: '인상파 걸작의 보고. 모네, 르누아르, 고흐, 세잔 작품 소장.',
            mustVisit: true,
            hours: '09:30~18:00 (목 ~21:45)',
            closedDay: '월요일',
            admission: '€16',
            duration: '2~3시간',
            latitude: 48.8600,
            longitude: 2.3266,
            rating: 4.7,
          },
        ],
      },
      {
        name: '몽마르트르',
        nameLocal: 'Montmartre',
        description: '예술가의 언덕. 사크레쾨르 대성당과 테르트르 광장의 화가들.',
        walkable: true,
        timeNeeded: '2~3시간',
        places: [
          {
            name: '사크레쾨르 대성당',
            nameLocal: 'Basilique du Sacré-Cœur',
            category: '관광지',
            description: '몽마르트르 언덕 정상의 하얀 대성당. 파리 시내 전경 무료 감상.',
            mustVisit: true,
            hours: '06:00~22:30',
            admission: '무료 (돔 €7)',
            duration: '1시간',
            latitude: 48.8867,
            longitude: 2.3431,
            rating: 4.6,
          },
          {
            name: '테르트르 광장',
            nameLocal: 'Place du Tertre',
            category: '관광지',
            description: '화가들이 즉석 초상화를 그리는 몽마르트르의 상징적 광장.',
            mustVisit: false,
            hours: '상시',
            duration: '30분',
            latitude: 48.8862,
            longitude: 2.3409,
            rating: 4.2,
          },
        ],
      },
    ],
    foods: [
      { name: '크루아상', nameLocal: 'Croissant', description: '겹겹이 층이 살아있는 버터 크루아상. 파리 아침의 필수.', priceRange: '€1.5~3', mustTry: true, bestSpots: ['뒤 팡 에 데 이데', '세드릭 그롤레'], mealType: 'breakfast' },
      { name: '프렌치 어니언 수프', nameLocal: 'Soupe à l\'oignon', description: '양파를 오래 볶아 만든 수프 위에 그뤼에르 치즈를 녹인 전통 요리.', priceRange: '€8~15', mustTry: true, bestSpots: ['르 피에 드 코숑'], mealType: 'dinner' },
      { name: '에스카르고', nameLocal: 'Escargots', description: '마늘 허브 버터에 구운 달팽이. 프랑스 요리의 상징.', priceRange: '€12~20', mustTry: true, bestSpots: ['라 메종 드 레스카르고'], mealType: 'dinner' },
      { name: '마카롱', nameLocal: 'Macaron', description: '알록달록한 프렌치 마카롱. 겉은 바삭 속은 촉촉.', priceRange: '€2~3 (개당)', mustTry: true, bestSpots: ['라뒤레', '피에르 에르메'], mealType: 'snack' },
    ],
    events: [
      { name: '바스티유 데이', nameLocal: 'Fête nationale (14 Juillet)', period: '7월 14일', description: '프랑스 혁명 기념일. 에펠탑 불꽃놀이와 샹젤리제 군사 퍼레이드.', highlight: '에펠탑 배경의 불꽃놀이가 최고 하이라이트' },
      { name: '뉘 블랑쉬', nameLocal: 'Nuit Blanche', period: '10월 첫째 토요일', description: '밤새 예술을 즐기는 파리의 밤. 미술관·갤러리 무료 개방.', highlight: '도시 곳곳의 야간 아트 설치물' },
    ],
    transportLinks: [
      { from: '인천', method: '직항', duration: '약 12시간', cost: '700,000~1,300,000원' },
      { from: 'CDG 공항→시내', method: 'RER B', duration: '약 35분', cost: '€11.45' },
    ],
    neighborCities: [
      { cityId: 'versailles', cityName: '베르사유', transport: 'RER C', duration: '약 40분', dayTripViable: true },
      { cityId: 'london', cityName: '런던', transport: '유로스타', duration: '약 2시간 15분', dayTripViable: false },
    ],
    travelTips: [
      '메트로 10회권(카르네) 또는 나비고 주간권 구매 추천',
      '미술관은 매달 첫째 일요일 무료인 곳이 많음',
      '레스토랑 서비스료는 가격에 포함. 추가 팁은 소액(€1~2)',
      '소매치기 주의: 메트로, 에펠탑 주변, 관광지 밀집 지역',
      '빵집(불랑주리)의 크루아상은 아침 일찍 가야 갓 구운 것을 먹을 수 있어요',
    ],
    tags: ['미술관', '낭만', '미식', '패션', '와인', '에펠탑', '세느강'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // LONDON
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'london',
    name: '런던',
    nameLocal: 'London',
    country: '영국',
    region: '서유럽',
    description: '대영박물관, 빅벤, 타워브릿지. 전통과 현대가 공존하는 세계적 도시.',
    character: '전통과 트렌드가 공존하는 왕실의 도시',
    bestSeasons: ['spring', 'summer'],
    averageStay: '4~6일',
    budgetPerDay: { economy: '120,000~200,000원', mid: '250,000~400,000원', premium: '500,000원~' },
    areas: [
      {
        name: '웨스트민스터',
        nameLocal: 'Westminster',
        description: '빅벤, 국회의사당, 웨스트민스터 사원, 버킹엄 궁전이 모인 정치·역사 중심.',
        walkable: true,
        timeNeeded: '반나절',
        places: [
          {
            name: '빅벤·국회의사당',
            nameLocal: 'Big Ben & Houses of Parliament',
            category: '관광지',
            description: '런던의 상징 빅벤. 템스 강변에서 바라보는 야경이 아름다움.',
            mustVisit: true,
            hours: '외부 상시',
            duration: '30분 (외부)',
            latitude: 51.5007,
            longitude: -0.1246,
            rating: 4.6,
          },
          {
            name: '버킹엄 궁전',
            nameLocal: 'Buckingham Palace',
            category: '관광지',
            description: '영국 왕실 공식 거주지. 근위병 교대식이 인기.',
            mustVisit: true,
            hours: '근위병 교대: 11:00 (매일/격일)',
            admission: '무료 (교대식)',
            duration: '1시간',
            latitude: 51.5014,
            longitude: -0.1419,
            rating: 4.5,
            tips: '교대식은 10:30까지 자리 잡기. 공식 사이트에서 일정 확인.',
          },
        ],
      },
      {
        name: '사우스 뱅크·시티',
        nameLocal: 'South Bank & The City',
        description: '템스 강변의 문화 지구. 테이트 모던, 타워 브릿지, 런던아이.',
        walkable: true,
        timeNeeded: '반나절',
        places: [
          {
            name: '대영박물관',
            nameLocal: 'British Museum',
            category: '관광지',
            description: '이집트 미라, 로제타 스톤, 파르테논 마블 등 세계 문명의 보고. 무료 입장.',
            mustVisit: true,
            hours: '10:00~17:00 (금 ~20:30)',
            admission: '무료',
            duration: '3~4시간',
            latitude: 51.5194,
            longitude: -0.1270,
            rating: 4.7,
          },
          {
            name: '타워 브릿지',
            nameLocal: 'Tower Bridge',
            category: '관광지',
            description: '1894년 개통된 런던의 아이코닉한 개폐식 다리.',
            mustVisit: true,
            hours: '09:30~18:00',
            admission: '£12.30 (전시 포함)',
            duration: '1시간',
            latitude: 51.5055,
            longitude: -0.0754,
            rating: 4.6,
          },
          {
            name: '테이트 모던',
            nameLocal: 'Tate Modern',
            category: '관광지',
            description: '화력발전소를 개조한 현대미술관. 피카소, 달리, 워홀 작품. 무료.',
            mustVisit: true,
            hours: '10:00~18:00 (금토 ~22:00)',
            admission: '무료 (특별전 별도)',
            duration: '2~3시간',
            latitude: 51.5076,
            longitude: -0.0994,
            rating: 4.6,
          },
        ],
      },
      {
        name: '캠던·노팅힐',
        nameLocal: 'Camden & Notting Hill',
        description: '개성 있는 마켓과 스트리트 문화. 런던의 힙한 면.',
        walkable: true,
        timeNeeded: '반나절',
        places: [
          {
            name: '캠던 마켓',
            nameLocal: 'Camden Market',
            category: '쇼핑',
            description: '빈티지 의류, 스트리트 푸드, 핸드메이드 제품의 천국.',
            mustVisit: true,
            hours: '10:00~18:00',
            duration: '2~3시간',
            latitude: 51.5413,
            longitude: -0.1466,
            rating: 4.4,
          },
          {
            name: '포토벨로 마켓',
            nameLocal: 'Portobello Road Market',
            category: '쇼핑',
            description: '노팅힐의 화려한 골동품·빈티지 마켓. 토요일이 메인.',
            mustVisit: false,
            hours: '토 08:00~17:00 (평일 축소 운영)',
            duration: '2시간',
            latitude: 51.5154,
            longitude: -0.2052,
            rating: 4.3,
          },
        ],
      },
    ],
    foods: [
      { name: '피시 앤 칩스', nameLocal: 'Fish and Chips', description: '바삭한 대구 튀김과 굵은 감자칩. 영국의 소울 푸드.', priceRange: '£8~15', mustTry: true, bestSpots: ['팝파이즈', '더 골든 하인드'], mealType: 'lunch' },
      { name: '선데이 로스트', nameLocal: 'Sunday Roast', description: '로스트 비프, 요크셔 푸딩, 그레이비. 영국 전통 일요 점심.', priceRange: '£15~25', mustTry: true, bestSpots: ['더 앵커', '블랙록'], mealType: 'lunch' },
      { name: '애프터눈 티', nameLocal: 'Afternoon Tea', description: '스콘, 핑거 샌드위치, 케이크와 함께하는 영국 전통 티타임.', priceRange: '£35~65', mustTry: true, bestSpots: ['포트넘 앤 메이슨', '더 리츠'], mealType: 'snack' },
      { name: '풀 잉글리시 브렉퍼스트', nameLocal: 'Full English Breakfast', description: '베이컨, 소시지, 달걀, 빈즈, 토스트로 구성된 영국식 아침.', priceRange: '£8~15', mustTry: false, bestSpots: ['테리스 카페', '리젠시 카페'], mealType: 'breakfast' },
    ],
    events: [
      { name: '트루핑 더 컬러', nameLocal: 'Trooping the Colour', period: '6월 둘째 토요일', description: '국왕 공식 생일 축하 군사 퍼레이드.', highlight: '버킹엄 궁전 발코니에서 왕실 가족 등장' },
      { name: '노팅힐 카니발', nameLocal: 'Notting Hill Carnival', period: '8월 마지막 주말', description: '유럽 최대 거리 축제. 카리브해 문화 퍼레이드.', highlight: '화려한 의상과 스틸 드럼 밴드의 퍼레이드' },
    ],
    transportLinks: [
      { from: '인천', method: '직항', duration: '약 12시간', cost: '700,000~1,200,000원' },
      { from: '히드로 공항→시내', method: '히드로 익스프레스', duration: '약 15분', cost: '£25' },
    ],
    neighborCities: [
      { cityId: 'oxford', cityName: '옥스퍼드', transport: '기차', duration: '약 1시간', dayTripViable: true },
      { cityId: 'paris', cityName: '파리', transport: '유로스타', duration: '약 2시간 15분', dayTripViable: false },
    ],
    travelTips: [
      '오이스터 카드 또는 컨택리스 결제로 대중교통 이용 (존 1~2 일일 상한 £8.10)',
      '대영박물관, 내셔널 갤러리, 테이트 모던 등 주요 미술관·박물관 무료',
      '팁은 레스토랑 10~12.5%, 서비스 차지가 포함되어 있으면 추가 불요',
      '우산은 항상 가지고 다니세요. 런던 날씨는 예측 불가',
      '뮤지컬은 레스터 스퀘어 TKTS 부스에서 당일 할인 구매 가능',
    ],
    tags: ['미술관', '왕실', '뮤지컬', '미식', '쇼핑', '역사', '무료관광지'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // BARCELONA
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'barcelona',
    name: '바르셀로나',
    nameLocal: 'Barcelona',
    country: '스페인',
    region: '남유럽',
    description: '가우디 건축, 지중해 해변, 타파스 문화가 어우러진 카탈루냐의 수도.',
    character: '가우디의 예술이 살아 숨 쉬는 지중해 도시',
    bestSeasons: ['spring', 'autumn'],
    averageStay: '3~5일',
    budgetPerDay: { economy: '80,000~150,000원', mid: '200,000~350,000원', premium: '500,000원~' },
    areas: [
      {
        name: '에이샴플라 (가우디 건축)',
        nameLocal: 'L\'Eixample',
        description: '사그라다 파밀리아, 카사 바트요, 카사 밀라 등 가우디 건축 밀집지.',
        walkable: true,
        timeNeeded: '반나절',
        places: [
          {
            name: '사그라다 파밀리아',
            nameLocal: 'Basílica de la Sagrada Família',
            category: '관광지',
            description: '가우디의 미완성 걸작. 1882년 착공, 현재도 건축 중인 세계문화유산.',
            mustVisit: true,
            hours: '09:00~20:00',
            admission: '€26',
            duration: '1.5~2시간',
            latitude: 41.4036,
            longitude: 2.1744,
            rating: 4.8,
            tips: '온라인 사전 예약 필수. 타워 입장은 별도 요금(€36). 오전 빛이 가장 아름다워요.',
          },
          {
            name: '카사 바트요',
            nameLocal: 'Casa Batlló',
            category: '관광지',
            description: '가우디의 해양 모티브 건축. AR 가이드로 건물의 세계를 체험.',
            mustVisit: true,
            hours: '09:00~21:00',
            admission: '€35',
            duration: '1~1.5시간',
            latitude: 41.3916,
            longitude: 2.1650,
            rating: 4.6,
          },
        ],
      },
      {
        name: '고딕 지구·람블라스',
        nameLocal: 'Barri Gòtic & La Rambla',
        description: '중세 골목길, 대성당, 보케리아 시장이 있는 바르셀로나의 구시가.',
        walkable: true,
        timeNeeded: '반나절',
        places: [
          {
            name: '고딕 지구',
            nameLocal: 'Barri Gòtic',
            category: '관광지',
            description: '로마 시대부터 이어진 바르셀로나의 역사 중심지. 좁은 골목 탐험.',
            mustVisit: true,
            hours: '상시',
            duration: '2시간',
            latitude: 41.3833,
            longitude: 2.1761,
            rating: 4.5,
          },
          {
            name: '보케리아 시장',
            nameLocal: 'Mercat de la Boqueria',
            category: '맛집',
            description: '람블라스 거리의 대표 식품 시장. 신선한 과일, 해산물, 타파스.',
            mustVisit: true,
            hours: '08:00~20:30',
            closedDay: '일요일',
            duration: '1~1.5시간',
            latitude: 41.3816,
            longitude: 2.1716,
            rating: 4.4,
            tips: '관광객 가격에 주의. 시장 안쪽으로 갈수록 합리적.',
          },
        ],
      },
      {
        name: '바르셀로네타·해변',
        nameLocal: 'Barceloneta',
        description: '지중해 해변과 해산물 레스토랑이 모인 해안 지역.',
        walkable: true,
        timeNeeded: '반나절',
        places: [
          {
            name: '바르셀로네타 비치',
            nameLocal: 'Platja de la Barceloneta',
            category: '비치',
            description: '시내에서 가장 가까운 지중해 해변. 수영, 일광욕, 비치 바.',
            mustVisit: true,
            hours: '상시',
            duration: '2~3시간',
            latitude: 41.3783,
            longitude: 2.1925,
            rating: 4.3,
          },
        ],
      },
    ],
    foods: [
      { name: '타파스', nameLocal: 'Tapas', description: '스페인 소량 안주 문화. 파타타스 브라바스, 하몽, 크로케타 등.', priceRange: '€3~8 (접시당)', mustTry: true, bestSpots: ['엘 샹페뇨', '칼 펩', '바르 카녜테'], mealType: 'dinner' },
      { name: '빠에야', nameLocal: 'Paella', description: '해산물과 사프란 밥의 조합. 지중해 미식의 대표.', priceRange: '€12~20', mustTry: true, bestSpots: ['7 포르테스', '바라캬'], mealType: 'lunch' },
      { name: '츄로스 콘 초콜라테', nameLocal: 'Churros con Chocolate', description: '바삭한 츄로스를 진한 핫초콜릿에 찍어 먹는 스페인 간식.', priceRange: '€4~7', mustTry: true, bestSpots: ['추레리아 마누엘 산 로만'], mealType: 'snack' },
      { name: '피데우아', nameLocal: 'Fideuà', description: '빠에야의 면 버전. 가는 파스타를 해산물 육수로 조리.', priceRange: '€12~18', mustTry: false, bestSpots: ['바르셀로네타 해산물 레스토랑'], mealType: 'lunch' },
    ],
    events: [
      { name: '라 메르세', nameLocal: 'La Mercè', period: '9월 24일 전후', description: '바르셀로나 수호성인 축제. 불꽃놀이, 인간탑, 거인 행렬.', highlight: '코레포크(불 달리기)와 인간탑(카스텔) 퍼포먼스' },
      { name: '산 호안 축제', nameLocal: 'Festa de Sant Joan', period: '6월 23일 밤', description: '하지를 축하하는 불꽃·해변 축제.', highlight: '해변에서 모닥불을 피우고 밤새 파티' },
    ],
    transportLinks: [
      { from: '인천', method: '직항/경유', duration: '약 13~16시간', cost: '600,000~1,200,000원' },
      { from: '엘 프라트 공항→시내', method: '아에로부스', duration: '약 35분', cost: '€7.75' },
    ],
    neighborCities: [
      { cityId: 'montserrat', cityName: '몬세라트', transport: '기차+케이블카', duration: '약 1시간 30분', dayTripViable: true },
      { cityId: 'girona', cityName: '지로나', transport: '기차', duration: '약 40분', dayTripViable: true },
    ],
    travelTips: [
      'T-캐주얼 교통카드 (10회권 €11.35) 구매 추천',
      '사그라다 파밀리아, 구엘 공원 등 가우디 건축은 반드시 사전 예약',
      '소매치기 주의: 람블라스 거리, 지하철, 해변이 특히 위험',
      '식사 시간이 늦음: 점심 14시, 저녁 21시가 현지인 기준',
      '일요일은 많은 상점이 문을 닫으니 쇼핑은 평일에',
    ],
    tags: ['가우디', '건축', '해변', '미식', '타파스', '축제', '지중해'],
  },
];
