import { CityProfile } from './types';

// ─── Japan City Data ───────────────────────────────────────

export const JAPAN_CITIES: CityProfile[] = [
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // KANAZAWA (金沢)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'kanazawa',
    name: '가나자와',
    nameLocal: '金沢',
    country: '일본',
    region: '호쿠리쿠',
    description: '에도 시대의 풍경이 살아 숨 쉬는 북륙의 교토. 전통 공예, 정원, 해산물의 도시.',
    character: '전통과 현대가 공존하는 우아한 소도시',
    bestSeasons: ['spring', 'autumn', 'winter'],
    averageStay: '2~3일',
    budgetPerDay: { economy: '8,000~12,000엔', mid: '15,000~25,000엔', premium: '30,000엔~' },
    areas: [
      {
        name: '히가시 차야가이',
        nameLocal: '東茶屋街',
        description: '에도 시대 게이샤 문화가 남아 있는 전통 찻집 거리. 금박 아이스크림과 전통 카페.',
        walkable: true,
        timeNeeded: '1.5~2시간',
        places: [
          {
            name: '히가시 차야가이',
            nameLocal: 'ひがし茶屋街',
            category: '관광지',
            description: '일본에서 가장 아름다운 게이샤 거리 중 하나. 목조 건물이 늘어선 운치 있는 골목.',
            mustVisit: true,
            hours: '상시 개방 (개별 상점 10:00~17:00)',
            duration: '1~1.5시간',
            latitude: 36.5725,
            longitude: 136.6637,
            rating: 4.6,
            tips: '오전 일찍 방문하면 한적하게 즐길 수 있어요.',
          },
          {
            name: '하쿠이치 금박 체험',
            nameLocal: '箔一',
            category: '체험',
            description: '가나자와 명물 금박 공예 체험. 금박 소프트크림도 유명.',
            mustVisit: true,
            hours: '09:00~18:00',
            admission: '체험 500~1,200엔',
            duration: '30분~1시간',
            latitude: 36.5721,
            longitude: 136.6632,
            rating: 4.4,
          },
        ],
      },
      {
        name: '겐로쿠엔 주변',
        nameLocal: '兼六園周辺',
        description: '일본 3대 정원 겐로쿠엔과 가나자와성을 중심으로 한 핵심 관광 에리어.',
        walkable: true,
        timeNeeded: '3~4시간',
        places: [
          {
            name: '겐로쿠엔',
            nameLocal: '兼六園',
            category: '관광지',
            description: '일본 3대 정원. 사계절 다른 아름다움, 특히 겨울 유키즈리(눈매달기)가 장관.',
            mustVisit: true,
            hours: '07:00~18:00 (계절별 변동)',
            admission: '320엔',
            duration: '1.5~2시간',
            bestTime: '오전 7시 개장 직후',
            latitude: 36.5625,
            longitude: 136.6625,
            rating: 4.7,
            tips: '이른 아침 무료 입장 가능한 시간대가 있어요 (계절별 확인).',
          },
          {
            name: '가나자와성 공원',
            nameLocal: '金沢城公園',
            category: '관광지',
            description: '마에다 가문의 거성. 이시카와몬 문이 상징적.',
            mustVisit: true,
            hours: '07:00~18:00',
            admission: '무료 (일부 건물 320엔)',
            duration: '1~1.5시간',
            latitude: 36.5636,
            longitude: 136.6592,
            rating: 4.5,
          },
          {
            name: '21세기 미술관',
            nameLocal: '金沢21世紀美術館',
            category: '관광지',
            description: '레안드로 에를리치의 수영장 작품으로 유명한 현대미술관. SNS 핫스팟.',
            mustVisit: true,
            hours: '10:00~18:00 (금토 ~20:00)',
            closedDay: '월요일',
            admission: '일반 450엔~',
            duration: '1.5~2시간',
            latitude: 36.5607,
            longitude: 136.6584,
            rating: 4.5,
            tips: '수영장 작품은 사전 예약 필수! 무료 존도 충분히 즐길 수 있어요.',
          },
        ],
      },
      {
        name: '오미초 시장',
        nameLocal: '近江町市場',
        description: '가나자와의 부엌. 신선한 해산물과 로컬 식재료의 보고.',
        walkable: true,
        timeNeeded: '1~2시간',
        places: [
          {
            name: '오미초 시장',
            nameLocal: '近江町市場',
            category: '맛집',
            description: '300년 역사의 시장. 해산물 덮밥, 노도구로, 게 등 신선한 먹거리.',
            mustVisit: true,
            hours: '09:00~17:00 (식당별 상이)',
            duration: '1~1.5시간',
            latitude: 36.5714,
            longitude: 136.6567,
            rating: 4.5,
            tips: '점심시간엔 줄이 깁니다. 11시 전에 도착 추천!',
          },
        ],
      },
      {
        name: '나가마치 무사 저택',
        nameLocal: '長町武家屋敷跡',
        description: '에도 시대 무사들의 주거지 거리. 토담길이 인상적.',
        walkable: true,
        timeNeeded: '1~1.5시간',
        places: [
          {
            name: '나가마치 부케야시키',
            nameLocal: '長町武家屋敷跡',
            category: '관광지',
            description: '보존 상태 좋은 무사 저택 거리. 노무라 가문 저택 내부 관람 가능.',
            mustVisit: false,
            hours: '08:30~17:30',
            admission: '550엔',
            duration: '45분~1시간',
            latitude: 36.5634,
            longitude: 136.6505,
            rating: 4.3,
          },
        ],
      },
    ],
    foods: [
      { name: '노도구로 (아카무쓰)', nameLocal: 'のどぐろ', description: '호쿠리쿠 대표 고급 생선. 회, 구이, 초밥 모두 일품.', priceRange: '3,000~8,000엔', mustTry: true, bestSpots: ['오미초 시장', '모리모리즈시'], mealType: 'any' },
      { name: '가나자와 카이센동', nameLocal: '金沢海鮮丼', description: '신선한 해산물을 가득 올린 덮밥. 오미초 시장의 대표 메뉴.', priceRange: '1,500~3,500엔', mustTry: true, bestSpots: ['오미초 시장 이키이키테이', '다이와'], mealType: 'lunch' },
      { name: '하쿠잇치 금박 소프트크림', nameLocal: '金箔ソフトクリーム', description: '가나자와 명물. 금박을 올린 소프트 아이스크림.', priceRange: '800~1,000엔', mustTry: true, bestSpots: ['하쿠이치 히가시야마점'], mealType: 'snack' },
      { name: '지부니', nameLocal: '治部煮', description: '가나자와 향토 요리. 오리고기와 채소를 밀가루로 걸쭉하게 조린 요리.', priceRange: '1,000~2,000엔', mustTry: false, bestSpots: ['이타루', '오토메즈시'], mealType: 'dinner' },
    ],
    events: [
      { name: '겐로쿠엔 유키즈리', nameLocal: '兼六園雪吊り', period: '11월 중순~3월 중순', description: '소나무에 눈 피해를 막기 위한 밧줄 매달기.', highlight: '눈 내린 겐로쿠엔은 일본에서 가장 아름다운 겨울 풍경 중 하나' },
      { name: '가나자와 백만석 축제', nameLocal: '金沢百万石まつり', period: '6월 첫째 주말', description: '마에다 도시이에의 입성을 기념하는 축제.', highlight: '시대 행렬이 시내를 순회' },
    ],
    transportLinks: [
      { from: '도쿄', method: '호쿠리쿠 신칸센', duration: '약 2시간 30분', cost: '14,380엔 (지정석)', tips: '카가야키(최속) 이용 추천' },
      { from: '오사카', method: '특급 선더버드', duration: '약 2시간 40분', cost: '7,790엔' },
    ],
    neighborCities: [
      { cityId: 'takayama', cityName: '다카야마', transport: '고속버스', duration: '약 2시간 15분', dayTripViable: false },
      { cityId: 'shirakawago', cityName: '시라카와고', transport: '고속버스', duration: '약 1시간 15분', dayTripViable: true },
    ],
    travelTips: [
      '가나자와 주유버스(1일권 800엔)로 주요 관광지 순환 가능',
      '오미초 시장은 수요일·일요일 휴무 가게가 많으니 확인 필수',
      '21세기 미술관 수영장 작품은 사전 온라인 예약 필요',
      '겨울(12~2월)에 오면 노도구로, 가니(게) 시즌과 유키즈리를 동시에 즐길 수 있어요',
    ],
    tags: ['전통', '정원', '해산물', '공예', '미술관', '겨울추천'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // SAPPORO (札幌)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'sapporo',
    name: '삿포로',
    nameLocal: '札幌',
    country: '일본',
    region: '홋카이도',
    description: '홋카이도의 중심 도시. 라멘, 맥주, 눈 축제의 도시. 자연과 도시가 조화.',
    character: '맛있는 음식과 시원한 자연의 활기찬 도시',
    bestSeasons: ['summer', 'winter'],
    averageStay: '2~3일',
    budgetPerDay: { economy: '8,000~12,000엔', mid: '15,000~22,000엔', premium: '30,000엔~' },
    areas: [
      {
        name: '오도리 공원·스스키노',
        nameLocal: '大通公園・すすきの',
        description: '삿포로의 심장부. 오도리 공원을 중심으로 TV탑, 스스키노 유흥가까지.',
        walkable: true,
        timeNeeded: '2~3시간',
        places: [
          {
            name: '오도리 공원',
            nameLocal: '大通公園',
            category: '관광지',
            description: '삿포로 중심에 1.5km 뻗은 공원. 눈축제, 라일락축제, 가을맥주축제 등 이벤트의 무대.',
            mustVisit: true,
            hours: '상시 개방',
            duration: '30분~1시간',
            latitude: 43.0596,
            longitude: 141.3545,
            rating: 4.3,
          },
          {
            name: '삿포로 TV탑',
            nameLocal: 'さっぽろテレビ塔',
            category: '관광지',
            description: '오도리 공원 동쪽 끝의 랜드마크. 전망대에서 공원 전체 조망.',
            mustVisit: false,
            hours: '09:00~22:00',
            admission: '1,000엔',
            duration: '30분',
            latitude: 43.0607,
            longitude: 141.3567,
            rating: 4.0,
          },
          {
            name: '니조 시장',
            nameLocal: '二条市場',
            category: '맛집',
            description: '100년 넘은 역사의 해산물 시장. 아침 해산물 덮밥이 인기.',
            mustVisit: true,
            hours: '07:00~18:00',
            duration: '1시간',
            latitude: 43.0578,
            longitude: 141.3570,
            rating: 4.2,
            tips: '아침식사 겸 방문 추천. 성게(우니) 덮밥이 일품.',
          },
        ],
      },
      {
        name: '삿포로역 주변',
        nameLocal: '札幌駅周辺',
        description: 'JR타워, 백화점, 지하상가가 밀집한 상업 중심지.',
        walkable: true,
        timeNeeded: '2~3시간',
        places: [
          {
            name: '삿포로 맥주 박물관',
            nameLocal: 'サッポロビール博物館',
            category: '체험',
            description: '일본 유일의 맥주 박물관. 시음 투어가 인기.',
            mustVisit: true,
            hours: '11:00~20:00',
            closedDay: '월요일',
            admission: '무료 (시음 투어 1,000엔)',
            duration: '1~1.5시간',
            latitude: 43.0655,
            longitude: 141.3668,
            rating: 4.3,
            tips: '프리미엄 투어(1,000엔)는 한정 맥주 시음 포함.',
          },
          {
            name: '삿포로 맥주원 징기스칸',
            nameLocal: 'サッポロビール園',
            category: '맛집',
            description: '삿포로 맥주와 홋카이도 양고기 징기스칸을 함께 즐기는 삿포로 대표 미식.',
            mustVisit: true,
            hours: '11:30~22:00',
            duration: '1.5시간',
            latitude: 43.0658,
            longitude: 141.3673,
            rating: 4.4,
          },
        ],
      },
      {
        name: '마루야마 공원·홋카이도 신궁',
        nameLocal: '円山公園・北海道神宮',
        description: '시내에서 가까운 자연 공간. 동물원, 신사, 산책로.',
        walkable: true,
        timeNeeded: '2~3시간',
        places: [
          {
            name: '홋카이도 신궁',
            nameLocal: '北海道神宮',
            category: '신사/사찰',
            description: '홋카이도 최대 신사. 벚꽃과 단풍 명소.',
            mustVisit: false,
            hours: '06:00~17:00 (계절별 변동)',
            admission: '무료',
            duration: '30분~1시간',
            latitude: 43.0533,
            longitude: 141.3081,
            rating: 4.4,
          },
        ],
      },
    ],
    foods: [
      { name: '삿포로 미소 라멘', nameLocal: '札幌味噌ラーメン', description: '홋카이도 버터·옥수수가 올라간 진한 미소 라멘. 삿포로의 영혼.', priceRange: '800~1,200엔', mustTry: true, bestSpots: ['스미레', '싯포로 라멘 요코초'], mealType: 'any' },
      { name: '징기스칸 (양고기 구이)', nameLocal: 'ジンギスカン', description: '홋카이도식 양고기 바비큐. 특제 소스에 찍어 먹는 것이 포인트.', priceRange: '1,500~3,000엔', mustTry: true, bestSpots: ['삿포로 맥주원', '다루마'], mealType: 'dinner' },
      { name: '해산물 덮밥', nameLocal: '海鮮丼', description: '성게, 연어알, 게 등 홋카이도산 해산물의 향연.', priceRange: '2,000~4,000엔', mustTry: true, bestSpots: ['니조 시장', '조가이 시장'], mealType: 'lunch' },
      { name: '스프 카레', nameLocal: 'スープカレー', description: '삿포로 발상의 독창적 카레. 큼직한 채소와 향신료 풍미.', priceRange: '1,000~1,800엔', mustTry: true, bestSpots: ['수아게+', '오쿠시바 카레'], mealType: 'lunch' },
      { name: '시로이 코이비토', nameLocal: '白い恋人', description: '삿포로 대표 기념품 과자. 공장 견학도 가능.', priceRange: '800~2,000엔', mustTry: false, bestSpots: ['시로이 코이비토 파크'], mealType: 'snack' },
    ],
    events: [
      { name: '삿포로 눈축제', nameLocal: 'さっぽろ雪まつり', period: '2월 초', description: '세계 3대 겨울 축제. 대형 눈/얼음 조각이 오도리 공원을 가득 채움.', highlight: '약 200개 이상의 눈/얼음 조각, 야간 라이트업' },
      { name: '삿포로 오텀 페스트', nameLocal: 'さっぽろオータムフェスト', period: '9~10월', description: '오도리 공원에서 열리는 대규모 음식 축제.', highlight: '홋카이도 각지의 맛을 한곳에서' },
    ],
    transportLinks: [
      { from: '도쿄', method: '비행기', duration: '약 1시간 30분', cost: '10,000~25,000엔 (LCC~JAL)', tips: '신치토세 공항에서 JR 쾌속으로 삿포로역까지 40분' },
      { from: '오사카', method: '비행기', duration: '약 2시간', cost: '8,000~20,000엔' },
    ],
    neighborCities: [
      { cityId: 'otaru', cityName: '오타루', transport: 'JR', duration: '약 35분', dayTripViable: true },
      { cityId: 'furano', cityName: '후라노', transport: 'JR+버스', duration: '약 2시간', dayTripViable: true },
    ],
    travelTips: [
      '지하철 1일권(830엔)으로 주요 관광지 이동 가능',
      '여름(7~8월)은 홋카이도 최적 시즌. 에어컨 없는 숙소도 있으니 확인',
      '겨울(12~2월) 방문 시 방한복 필수. 길이 얼어 미끄러우니 신발 주의',
      '렌터카 이용 시 홋카이도 외곽까지 여행 반경이 확 넓어져요',
    ],
    tags: ['라멘', '맥주', '눈축제', '해산물', '자연', '겨울추천', '여름추천'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // KOBE (神戸)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'kobe',
    name: '고베',
    nameLocal: '神戸',
    country: '일본',
    region: '간사이',
    description: '산과 바다 사이의 이국적인 항구 도시. 와규의 본고장이자 야경의 도시.',
    character: '세련되고 이국적인 항구 도시',
    bestSeasons: ['spring', 'autumn'],
    averageStay: '1~2일',
    budgetPerDay: { economy: '8,000~12,000엔', mid: '15,000~25,000엔', premium: '35,000엔~' },
    areas: [
      {
        name: '기타노이진칸',
        nameLocal: '北野異人館',
        description: '메이지 시대 외국인 저택이 모인 이국적 언덕 마을.',
        walkable: true,
        timeNeeded: '2~3시간',
        places: [
          {
            name: '기타노이진칸',
            nameLocal: '北野異人館街',
            category: '관광지',
            description: '19세기 서양식 저택이 늘어선 이국적 거리. 풍향계의 집, 사쓰마의 집 등.',
            mustVisit: true,
            hours: '09:00~18:00',
            admission: '각 500~700엔 (패스권 3,000엔)',
            duration: '2~3시간',
            latitude: 34.7020,
            longitude: 135.1898,
            rating: 4.3,
            tips: '스타벅스 기타노이진칸점은 등록문화재 건물이에요.',
          },
        ],
      },
      {
        name: '난킨마치·하버랜드',
        nameLocal: '南京町・ハーバーランド',
        description: '차이나타운에서 항구까지 걸어서 즐기는 고베의 핵심 코스.',
        walkable: true,
        timeNeeded: '3~4시간',
        places: [
          {
            name: '난킨마치 (고베 차이나타운)',
            nameLocal: '南京町',
            category: '맛집',
            description: '일본 3대 차이나타운. 부타만(돼지고기만두)이 대표 먹거리.',
            mustVisit: true,
            hours: '11:00~21:00',
            duration: '1시간',
            latitude: 34.6876,
            longitude: 135.1754,
            rating: 4.2,
          },
          {
            name: '고베 하버랜드 모자이크',
            nameLocal: '神戸ハーバーランドモザイク',
            category: '쇼핑',
            description: '항구 전망의 쇼핑·레스토랑 복합시설. 고베 포트타워 뷰가 환상.',
            mustVisit: true,
            hours: '10:00~21:00',
            duration: '1.5~2시간',
            bestTime: '저녁 야경 타이밍',
            latitude: 34.6796,
            longitude: 135.1846,
            rating: 4.3,
          },
        ],
      },
      {
        name: '롯코산',
        nameLocal: '六甲山',
        description: '고베를 내려다보는 산. 1000만 달러 야경의 무대.',
        walkable: false,
        timeNeeded: '반나절',
        places: [
          {
            name: '롯코산 전망대',
            nameLocal: '六甲山展望台',
            category: '자연',
            description: '고베·오사카만의 1000만 달러 야경. 일본 3대 야경.',
            mustVisit: true,
            hours: '일몰~21:00',
            admission: '310엔',
            duration: '1시간',
            bestTime: '해질녘~야간',
            latitude: 34.7646,
            longitude: 135.2439,
            rating: 4.6,
          },
        ],
      },
    ],
    foods: [
      { name: '고베규 (고베 소고기)', nameLocal: '神戸牛', description: '세계적으로 유명한 와규. 마블링이 예술적인 최고급 소고기.', priceRange: '5,000~20,000엔', mustTry: true, bestSpots: ['모리야', '스테이크랜드', '와쿠오'], mealType: 'dinner' },
      { name: '부타만 (돼지고기 만두)', nameLocal: '豚まん', description: '난킨마치 명물. 육즙 가득한 찐빵.', priceRange: '300~500엔', mustTry: true, bestSpots: ['로쇼키', '주니반가이'], mealType: 'snack' },
      { name: '고베 스위츠', nameLocal: '神戸スイーツ', description: '일본 양과자 발상지. 치즈케이크, 푸딩 등.', priceRange: '500~1,000엔', mustTry: false, bestSpots: ['콘디토라이 고베', '모로조프'], mealType: 'snack' },
    ],
    events: [
      { name: '고베 루미나리에', nameLocal: '神戸ルミナリエ', period: '12월', description: '한신대지진 추모 일루미네이션. 아름다운 빛의 터널.', highlight: '수십만 개 LED로 만든 아치형 빛의 회랑' },
    ],
    transportLinks: [
      { from: '도쿄', method: '신칸센', duration: '약 2시간 40분', cost: '15,000엔 (노조미)', tips: '신고베역 하차' },
      { from: '오사카', method: 'JR', duration: '약 21분', cost: '420엔' },
    ],
    neighborCities: [
      { cityId: 'himeji', cityName: '히메지', transport: 'JR', duration: '약 40분', dayTripViable: true },
      { cityId: 'arima', cityName: '아리마 온천', transport: '버스', duration: '약 30분', dayTripViable: true },
    ],
    travelTips: [
      '오사카에서 당일치기로 충분히 가능 (JR 21분)',
      '고베규는 점심 세트가 저녁보다 훨씬 저렴해요 (런치 3,000엔대부터)',
      '시티 루프 버스(1일권 700엔)로 주요 관광지 순환',
      '롯코산 야경은 케이블카+버스 조합으로 가요',
    ],
    tags: ['와규', '항구', '야경', '이국적', '스위츠', '당일치기'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // KAGOSHIMA (鹿児島)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'kagoshima',
    name: '가고시마',
    nameLocal: '鹿児島',
    country: '일본',
    region: '규슈',
    description: '활화산 사쿠라지마를 마주한 남국 도시. 흑돼지, 온천, 사쓰마 역사의 땅.',
    character: '화산과 함께 사는 남국의 활력',
    bestSeasons: ['spring', 'autumn'],
    averageStay: '2~3일',
    budgetPerDay: { economy: '7,000~10,000엔', mid: '12,000~20,000엔', premium: '25,000엔~' },
    areas: [
      {
        name: '사쿠라지마',
        nameLocal: '桜島',
        description: '가고시마의 상징인 활화산. 페리로 15분.',
        walkable: false,
        timeNeeded: '반나절',
        places: [
          {
            name: '사쿠라지마',
            nameLocal: '桜島',
            category: '자연',
            description: '현재도 활동 중인 화산. 전망대, 용암 해변, 족욕 온천 등.',
            mustVisit: true,
            hours: '상시 (페리 24시간 운항)',
            admission: '페리 200엔',
            duration: '3~4시간',
            latitude: 31.5811,
            longitude: 130.6572,
            rating: 4.5,
            tips: '사쿠라지마 아일랜드뷰 버스(1일권 500엔)로 순환 가능.',
          },
        ],
      },
      {
        name: '텐몬칸·시내 중심',
        nameLocal: '天文館・市内',
        description: '가고시마 최대 번화가. 쇼핑, 맛집, 역사.',
        walkable: true,
        timeNeeded: '2~3시간',
        places: [
          {
            name: '센간엔 (시마즈 정원)',
            nameLocal: '仙巌園',
            category: '관광지',
            description: '사쿠라지마를 차경으로 한 시마즈 가문의 정원. 세계유산.',
            mustVisit: true,
            hours: '09:00~17:00',
            admission: '1,000엔',
            duration: '1.5~2시간',
            latitude: 31.6161,
            longitude: 130.5806,
            rating: 4.5,
            tips: '정원 카페에서 사쿠라지마를 보며 차 한잔 추천.',
          },
          {
            name: '텐몬칸 상점가',
            nameLocal: '天文館通り',
            category: '쇼핑',
            description: '가고시마 최대 아케이드. 시로쿠마 빙수, 흑돼지 맛집 밀집.',
            mustVisit: true,
            hours: '10:00~21:00',
            duration: '1~2시간',
            latitude: 31.5888,
            longitude: 130.5563,
            rating: 4.1,
          },
        ],
      },
    ],
    foods: [
      { name: '가고시마 흑돼지', nameLocal: '黒豚', description: '사쓰마 흑돼지 돈가스·샤브샤브. 달콤하고 부드러운 맛.', priceRange: '1,500~3,000엔', mustTry: true, bestSpots: ['쿠로가츠테이', '아지노토쿠오'], mealType: 'lunch' },
      { name: '시로쿠마 빙수', nameLocal: '白くま', description: '가고시마 발상 프루츠 빙수. 곰돌이 얼굴 형태.', priceRange: '500~800엔', mustTry: true, bestSpots: ['텐몬칸 무쟈키'], mealType: 'snack' },
      { name: '키비나고', nameLocal: 'きびなご', description: '가고시마 특산 은빛 작은 생선. 회, 튀김, 구이로.', priceRange: '500~1,000엔', mustTry: false, bestSpots: ['텐몬칸 이자카야'], mealType: 'dinner' },
    ],
    events: [
      { name: '오하라마츠리', nameLocal: 'おはら祭', period: '11월', description: '2만 명이 춤추는 가고시마 최대 축제.', highlight: '가고시마 거리를 가득 메우는 군무' },
    ],
    transportLinks: [
      { from: '도쿄', method: '비행기', duration: '약 1시간 50분', cost: '10,000~25,000엔' },
      { from: '오사카', method: '신칸센 미즈호', duration: '약 3시간 40분', cost: '21,000엔' },
    ],
    neighborCities: [
      { cityId: 'yakushima', cityName: '야쿠시마', transport: '고속선', duration: '약 2시간', dayTripViable: false },
      { cityId: 'ibusuki', cityName: '이부스키', transport: 'JR', duration: '약 1시간', dayTripViable: true },
    ],
    travelTips: [
      '시내 노면전차 1일권(600엔)으로 이동 편리',
      '사쿠라지마 페리는 24시간 운항, 야경 시간대 추천',
      '화산재가 날릴 수 있으니 마스크 준비',
      '이부스키의 모래찜질 온천은 꼭 체험해보세요 (당일치기 가능)',
    ],
    tags: ['화산', '흑돼지', '온천', '남국', '역사', '자연'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // HIROSHIMA (広島)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'hiroshima',
    name: '히로시마',
    nameLocal: '広島',
    country: '일본',
    region: '추고쿠',
    description: '평화의 도시이자 오코노미야키의 본고장. 미야지마(이쓰쿠시마)와 함께.',
    character: '평화와 미식의 따뜻한 도시',
    bestSeasons: ['spring', 'autumn'],
    averageStay: '2~3일',
    budgetPerDay: { economy: '7,000~10,000엔', mid: '12,000~20,000엔', premium: '25,000엔~' },
    areas: [
      {
        name: '평화기념공원',
        nameLocal: '平和記念公園',
        description: '원폭의 역사와 평화의 메시지를 전하는 장소.',
        walkable: true,
        timeNeeded: '2~3시간',
        places: [
          {
            name: '히로시마 평화기념 자료관',
            nameLocal: '広島平和記念資料館',
            category: '관광지',
            description: '원폭의 역사를 기록한 박물관. 감동적이고 교육적.',
            mustVisit: true,
            hours: '08:30~18:00',
            admission: '200엔',
            duration: '1.5~2시간',
            latitude: 34.3916,
            longitude: 132.4531,
            rating: 4.7,
            tips: '시간 여유를 갖고 천천히 관람하세요.',
          },
          {
            name: '원폭 돔',
            nameLocal: '原爆ドーム',
            category: '관광지',
            description: '세계유산. 원폭의 참화를 전하는 상징적 건물.',
            mustVisit: true,
            hours: '외관 상시',
            admission: '무료',
            duration: '30분',
            latitude: 34.3955,
            longitude: 132.4536,
            rating: 4.8,
          },
        ],
      },
      {
        name: '미야지마 (이쓰쿠시마)',
        nameLocal: '宮島',
        description: '바다 위 도리이로 유명한 세계유산 섬. 히로시마에서 페리로 이동.',
        walkable: true,
        timeNeeded: '반나절~1일',
        places: [
          {
            name: '이쓰쿠시마 신사',
            nameLocal: '厳島神社',
            category: '신사/사찰',
            description: '바다 위에 떠 있는 듯한 신사. 대도리이가 상징. 세계유산.',
            mustVisit: true,
            hours: '06:30~18:00',
            admission: '300엔',
            duration: '1시간',
            bestTime: '만조 시 바다 위 도리이 / 간조 시 걸어서 접근',
            latitude: 34.2961,
            longitude: 132.3199,
            rating: 4.7,
            tips: '조수 시간표를 미리 확인하세요!',
          },
          {
            name: '미야지마 상점가',
            nameLocal: '宮島表参道商店街',
            category: '쇼핑',
            description: '모미지 만주, 구운 굴, 아나고(붕장어) 등 먹거리 거리.',
            mustVisit: true,
            hours: '09:00~17:00',
            duration: '1시간',
            latitude: 34.2977,
            longitude: 132.3193,
            rating: 4.3,
          },
        ],
      },
    ],
    foods: [
      { name: '히로시마풍 오코노미야키', nameLocal: '広島風お好み焼き', description: '반죽·캐비지·면·소스를 겹겹이 쌓는 히로시마 소울 푸드.', priceRange: '800~1,500엔', mustTry: true, bestSpots: ['나기사', '미치야스', '오코노미무라'], mealType: 'lunch' },
      { name: '굴 (카키)', nameLocal: '牡蠣', description: '히로시마는 일본 최대 굴 산지. 구이, 튀김, 생굴.', priceRange: '500~2,000엔', mustTry: true, bestSpots: ['미야지마 상점가', '카키 고야'], mealType: 'any' },
      { name: '아나고 (붕장어)', nameLocal: 'あなご', description: '미야지마 명물. 아나고메시(붕장어 덮밥)가 대표.', priceRange: '1,500~2,500엔', mustTry: true, bestSpots: ['우에노', '후지타야'], mealType: 'lunch' },
      { name: '모미지 만주', nameLocal: 'もみじ饅頭', description: '단풍잎 모양 만주. 미야지마·히로시마 대표 기념품.', priceRange: '200~300엔', mustTry: false, bestSpots: ['미야지마 상점가'], mealType: 'snack' },
    ],
    events: [
      { name: '히로시마 평화기념식', nameLocal: '平和記念式典', period: '8월 6일', description: '원폭 투하일 추모 행사.', highlight: '등불 흘리기 행사가 감동적' },
    ],
    transportLinks: [
      { from: '도쿄', method: '신칸센 노조미', duration: '약 3시간 45분', cost: '19,440엔' },
      { from: '오사카', method: '신칸센 노조미', duration: '약 1시간 20분', cost: '10,400엔' },
    ],
    neighborCities: [
      { cityId: 'onomichi', cityName: '오노미치', transport: 'JR', duration: '약 1시간 20분', dayTripViable: true },
      { cityId: 'iwakuni', cityName: '이와쿠니', transport: 'JR', duration: '약 50분', dayTripViable: true },
    ],
    travelTips: [
      '히로시마·미야지마 프리패스(1,000엔) 이용하면 미야지마 페리 포함 할인',
      '미야지마는 반나절 이상 소요. 아침 일찍 출발 권장',
      '오코노미무라 빌딩(4층 전체가 오코노미야키점)은 관광객에게 편리',
      '사슴이 물건을 빼앗아 가니 미야지마에서 음식·지도 조심',
    ],
    tags: ['평화', '오코노미야키', '세계유산', '바다', '미야지마', '굴'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TOKYO (東京)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'tokyo',
    name: '도쿄',
    nameLocal: '東京',
    country: '일본',
    region: '간토',
    description: '일본의 수도. 전통과 초현대가 공존하는 세계 최대의 메트로폴리스.',
    character: '끝없이 새로운 것을 발견하는 거대 도시',
    bestSeasons: ['spring', 'autumn'],
    averageStay: '3~5일',
    budgetPerDay: { economy: '10,000~15,000엔', mid: '20,000~35,000엔', premium: '50,000엔~' },
    areas: [
      {
        name: '아사쿠사·우에노',
        nameLocal: '浅草・上野',
        description: '에도 시대의 정취가 남아 있는 전통 지역. 센소지와 아메요코.',
        walkable: true,
        timeNeeded: '3~4시간',
        places: [
          {
            name: '센소지 (아사쿠사)',
            nameLocal: '浅草寺',
            category: '신사/사찰',
            description: '도쿄 최고(最古)의 사찰. 가미나리몬과 나카미세 상점가가 유명.',
            mustVisit: true,
            hours: '06:00~17:00 (경내 상시)',
            admission: '무료',
            duration: '1~1.5시간',
            latitude: 35.7148,
            longitude: 139.7967,
            rating: 4.5,
            tips: '이른 아침(6~7시)에 방문하면 인파 없이 사진 촬영 가능.',
          },
          {
            name: '아메요코 상점가',
            nameLocal: 'アメ横商店街',
            category: '쇼핑',
            description: '우에노역 옆 활기찬 시장. 해산물, 의류, 과자 등 저렴한 쇼핑.',
            mustVisit: true,
            hours: '10:00~19:00',
            duration: '1~1.5시간',
            latitude: 35.7106,
            longitude: 139.7747,
            rating: 4.2,
            tips: '과일 꼬치, 케밥 등 길거리 음식이 풍부해요.',
          },
          {
            name: '우에노 공원',
            nameLocal: '上野恩賜公園',
            category: '관광지',
            description: '박물관, 미술관, 동물원이 모인 문화 공간. 봄 벚꽃 명소.',
            mustVisit: true,
            hours: '05:00~23:00',
            admission: '무료 (시설별 별도)',
            duration: '2~3시간',
            latitude: 35.7146,
            longitude: 139.7732,
            rating: 4.4,
          },
        ],
      },
      {
        name: '시부야·하라주쿠',
        nameLocal: '渋谷・原宿',
        description: '젊은 문화의 중심. 트렌드, 패션, 카페의 메카.',
        walkable: true,
        timeNeeded: '3~4시간',
        places: [
          {
            name: '시부야 스크램블 교차로',
            nameLocal: '渋谷スクランブル交差点',
            category: '관광지',
            description: '세계에서 가장 유명한 교차로. 한 번에 3,000명이 건너는 장관.',
            mustVisit: true,
            hours: '상시',
            admission: '무료',
            duration: '30분',
            latitude: 35.6595,
            longitude: 139.7004,
            rating: 4.3,
            tips: '스타벅스 시부야 츠타야점 2층에서 교차로 전경을 볼 수 있어요.',
          },
          {
            name: '메이지 신궁',
            nameLocal: '明治神宮',
            category: '신사/사찰',
            description: '도심 속 숲에 둘러싸인 신사. 하라주쿠역 바로 옆.',
            mustVisit: true,
            hours: '일출~일몰',
            admission: '무료',
            duration: '1시간',
            latitude: 35.6764,
            longitude: 139.6993,
            rating: 4.6,
          },
          {
            name: '다케시타도리',
            nameLocal: '竹下通り',
            category: '쇼핑',
            description: '하라주쿠의 상징. 카와이이 문화, 크레이프, 빈티지 숍.',
            mustVisit: true,
            hours: '10:00~20:00',
            duration: '1시간',
            latitude: 35.6709,
            longitude: 139.7025,
            rating: 4.0,
          },
        ],
      },
      {
        name: '신주쿠',
        nameLocal: '新宿',
        description: '도쿄 최대 번화가. 백화점, 이자카야, 가부키쵸, 도청 전망대.',
        walkable: true,
        timeNeeded: '2~4시간',
        places: [
          {
            name: '도쿄 도청 전망대',
            nameLocal: '東京都庁展望室',
            category: '관광지',
            description: '45층 무료 전망대. 후지산까지 보이는 날도.',
            mustVisit: true,
            hours: '09:30~23:00',
            admission: '무료',
            duration: '30분',
            latitude: 35.6896,
            longitude: 139.6922,
            rating: 4.3,
            tips: '도쿄타워보다 무료라서 가성비 최고. 야경도 훌륭해요.',
          },
          {
            name: '오모이데요코쵸',
            nameLocal: '思い出横丁',
            category: '맛집',
            description: '신주쿠역 서쪽의 좁은 골목 이자카야 거리. 레트로 분위기.',
            mustVisit: false,
            hours: '17:00~24:00',
            duration: '1~1.5시간',
            latitude: 35.6938,
            longitude: 139.6989,
            rating: 4.2,
          },
        ],
      },
      {
        name: '아키하바라·도쿄역',
        nameLocal: '秋葉原・東京駅',
        description: '오타쿠 문화의 성지와 마루노우치의 세련됨이 공존.',
        walkable: true,
        timeNeeded: '2~3시간',
        places: [
          {
            name: '아키하바라',
            nameLocal: '秋葉原',
            category: '쇼핑',
            description: '전자제품·애니메이션·피규어의 성지. 메이드 카페도 유명.',
            mustVisit: true,
            hours: '10:00~21:00',
            duration: '2~3시간',
            latitude: 35.6994,
            longitude: 139.7711,
            rating: 4.3,
          },
          {
            name: '도쿄역 이치방가이',
            nameLocal: '東京駅一番街',
            category: '쇼핑',
            description: '캐릭터 스트리트, 라멘 스트리트 등 테마별 쇼핑 거리.',
            mustVisit: false,
            hours: '10:00~20:30',
            duration: '1시간',
            latitude: 35.6812,
            longitude: 139.7671,
            rating: 4.1,
          },
        ],
      },
      {
        name: '오다이바·도요스',
        nameLocal: 'お台場・豊洲',
        description: '도쿄만 워터프론트. 팀랩, 도요스 시장, 쇼핑몰.',
        walkable: false,
        timeNeeded: '반나절',
        places: [
          {
            name: '팀랩 보더리스',
            nameLocal: 'チームラボボーダレス',
            category: '체험',
            description: '몰입형 디지털 아트 미술관. SNS 필수 스팟.',
            mustVisit: true,
            hours: '10:00~19:00',
            admission: '3,800엔',
            duration: '1.5~2시간',
            bestTime: '평일 오전',
            latitude: 35.6256,
            longitude: 139.7769,
            rating: 4.6,
            tips: '사전 온라인 예약 필수. 주말은 매진이 빨라요.',
          },
          {
            name: '도요스 시장',
            nameLocal: '豊洲市場',
            category: '맛집',
            description: '구 츠키지 이전 시장. 참치 경매 견학, 초밥 맛집 밀집.',
            mustVisit: true,
            hours: '05:00~15:00 (식당 ~14:00)',
            closedDay: '일요일·공휴일·수요일(격주)',
            duration: '1.5~2시간',
            latitude: 35.6455,
            longitude: 139.7830,
            rating: 4.4,
            tips: '참치 경매 견학은 새벽 5시부터. 식사만 할 거면 7시 이후 추천.',
          },
        ],
      },
    ],
    foods: [
      { name: '에도마에 스시', nameLocal: '江戸前寿司', description: '도쿄만 해산물로 만드는 전통 초밥. 장인의 기술이 살아 있는 카운터 스시.', priceRange: '3,000~20,000엔', mustTry: true, bestSpots: ['도요스 시장 스시다이', '스시야 사이토', '미도리즈시'], mealType: 'lunch' },
      { name: '라멘', nameLocal: 'ラーメン', description: '도쿄 라멘은 쇼유(간장) 베이스가 원조. 지역별로 다양한 스타일.', priceRange: '800~1,500엔', mustTry: true, bestSpots: ['후우인야', '이치란', '아후리'], mealType: 'any' },
      { name: '몬자야키', nameLocal: 'もんじゃ焼き', description: '도쿄 츠키시마 명물. 묽은 반죽을 철판에 구워 먹는 서민 음식.', priceRange: '1,000~2,000엔', mustTry: true, bestSpots: ['츠키시마 몬자 스트리트'], mealType: 'lunch' },
      { name: '텐동 (튀김덮밥)', nameLocal: '天丼', description: '바삭한 텐푸라를 밥 위에 올린 도쿄식 덮밥.', priceRange: '1,000~2,500엔', mustTry: false, bestSpots: ['카네코 한노스케', '텐야'], mealType: 'lunch' },
      { name: '야키토리', nameLocal: '焼き鳥', description: '숯불에 구운 닭꼬치. 이자카야의 필수 안주.', priceRange: '500~2,000엔', mustTry: true, bestSpots: ['오모이데요코쵸', '토리키조쿠'], mealType: 'dinner' },
    ],
    events: [
      { name: '벚꽃 시즌', nameLocal: '桜のシーズン', period: '3월 말~4월 초', description: '우에노·치도리가후치·메구로강 등 벚꽃 명소에서 하나미.', highlight: '치도리가후치 보트에서 벚꽃 터널 감상' },
      { name: '산자마츠리', nameLocal: '三社祭', period: '5월 셋째 주말', description: '아사쿠사 최대 축제. 100개 이상의 미코시(신여)가 거리를 누빔.', highlight: '에도의 열기를 느끼는 도쿄 3대 축제' },
      { name: '코미케', nameLocal: 'コミケ', period: '8월·12월', description: '세계 최대 동인지 즉매회. 오타쿠 문화의 정점.', highlight: '도쿄 빅사이트에서 3일간 50만 명 이상 참가' },
    ],
    transportLinks: [
      { from: '도쿄', method: '-', duration: '-', cost: '-' },
      { from: '오사카', method: '신칸센 노조미', duration: '약 2시간 15분', cost: '14,720엔' },
    ],
    neighborCities: [
      { cityId: 'yokohama', cityName: '요코하마', transport: 'JR/도큐 도요코선', duration: '약 25분', dayTripViable: true },
      { cityId: 'kamakura', cityName: '가마쿠라', transport: 'JR', duration: '약 55분', dayTripViable: true },
      { cityId: 'nikko', cityName: '닛코', transport: '도부 특급', duration: '약 1시간 50분', dayTripViable: true },
      { cityId: 'hakone', cityName: '하코네', transport: '오다큐 로망스카', duration: '약 1시간 15분', dayTripViable: true },
    ],
    travelTips: [
      'Suica/PASMO 교통카드 하나로 전철·버스·편의점 결제 가능',
      '도쿄 메트로 24시간권(600엔)이 가성비 최고',
      '신주쿠역은 세계에서 가장 복잡한 역. 구글맵 출구 번호 확인 필수',
      '라멘집은 식권기(티켓머신)가 보통. 투입→버튼→식권을 점원에게',
      '100엔 숍(다이소, 세리아)에서 여행용품 저렴하게 구입 가능',
      '편의점(세븐일레븐, 패밀리마트) 도시락이 의외로 맛있어요',
    ],
    tags: ['수도', '쇼핑', '맛집', '문화', '애니메이션', '벚꽃', '야경'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // OSAKA (大阪)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'osaka',
    name: '오사카',
    nameLocal: '大阪',
    country: '일본',
    region: '간사이',
    description: '먹다 쓰러지는 미식의 도시. 활기찬 상인 문화와 유머의 도시.',
    character: '먹고, 웃고, 즐기는 에너지 넘치는 도시',
    bestSeasons: ['spring', 'autumn'],
    averageStay: '2~4일',
    budgetPerDay: { economy: '8,000~12,000엔', mid: '15,000~25,000엔', premium: '35,000엔~' },
    areas: [
      {
        name: '도톤보리·난바',
        nameLocal: '道頓堀・難波',
        description: '오사카의 심장. 글리코 간판, 먹거리 천국, 쇼핑의 중심.',
        walkable: true,
        timeNeeded: '3~4시간',
        places: [
          {
            name: '도톤보리',
            nameLocal: '道頓堀',
            category: '관광지',
            description: '글리코 간판, 거대 게 간판 등 화려한 네온사인의 거리. 오사카의 상징.',
            mustVisit: true,
            hours: '상시 (가게 11:00~23:00)',
            admission: '무료',
            duration: '1.5~2시간',
            latitude: 34.6687,
            longitude: 135.5013,
            rating: 4.4,
            tips: '야간에 네온사인이 더 화려해요. 도톤보리 강변 산책 추천.',
          },
          {
            name: '구로몬 시장',
            nameLocal: '黒門市場',
            category: '맛집',
            description: '오사카의 부엌. 신선한 해산물, 과일, 꼬치 등 먹거리 풍부.',
            mustVisit: true,
            hours: '09:00~18:00',
            duration: '1~1.5시간',
            latitude: 34.6669,
            longitude: 135.5060,
            rating: 4.2,
            tips: '참치 해체쇼가 있는 날이면 럭키!',
          },
          {
            name: '신사이바시스지',
            nameLocal: '心斎橋筋商店街',
            category: '쇼핑',
            description: '600m 아케이드 쇼핑가. 브랜드숍, 드럭스토어, 의류점 밀집.',
            mustVisit: true,
            hours: '10:00~21:00',
            duration: '1~2시간',
            latitude: 34.6726,
            longitude: 135.5007,
            rating: 4.1,
          },
        ],
      },
      {
        name: '오사카성·텐노지',
        nameLocal: '大阪城・天王寺',
        description: '역사의 오사카성과 아베노 하루카스의 스카이라인.',
        walkable: true,
        timeNeeded: '2~3시간',
        places: [
          {
            name: '오사카성',
            nameLocal: '大阪城',
            category: '관광지',
            description: '도요토미 히데요시가 세운 상징적 성. 천수각 전망대에서 시내 조망.',
            mustVisit: true,
            hours: '09:00~17:00',
            admission: '600엔',
            duration: '1.5~2시간',
            latitude: 34.6873,
            longitude: 135.5262,
            rating: 4.4,
            tips: '봄 벚꽃, 가을 단풍 시즌에 특히 아름다워요.',
          },
          {
            name: '아베노 하루카스',
            nameLocal: 'あべのハルカス',
            category: '관광지',
            description: '일본에서 가장 높은 빌딩(300m). 전망대에서 오사카 전경.',
            mustVisit: false,
            hours: '09:00~22:00',
            admission: '1,500엔',
            duration: '1시간',
            latitude: 34.6462,
            longitude: 135.5134,
            rating: 4.3,
          },
        ],
      },
      {
        name: '신세카이·쓰텐카쿠',
        nameLocal: '新世界・通天閣',
        description: '레트로 분위기의 서민 거리. 쿠시카츠의 본고장.',
        walkable: true,
        timeNeeded: '1.5~2시간',
        places: [
          {
            name: '쓰텐카쿠',
            nameLocal: '通天閣',
            category: '관광지',
            description: '오사카의 에펠탑. 레트로 전망탑에서 신세카이 조망.',
            mustVisit: true,
            hours: '10:00~20:00',
            admission: '900엔',
            duration: '30분~1시간',
            latitude: 34.6525,
            longitude: 135.5062,
            rating: 4.0,
          },
        ],
      },
      {
        name: 'USJ (유니버설 스튜디오)',
        nameLocal: 'USJ',
        description: '해리포터, 마리오 등 인기 테마파크.',
        walkable: true,
        timeNeeded: '1일',
        places: [
          {
            name: '유니버설 스튜디오 재팬',
            nameLocal: 'ユニバーサル・スタジオ・ジャパン',
            category: '체험',
            description: '해리포터, 슈퍼닌텐도월드 등 인기 어트랙션. 오사카 필수 코스.',
            mustVisit: true,
            hours: '09:00~21:00 (시즌별 변동)',
            admission: '8,600엔~',
            duration: '8~10시간',
            latitude: 34.6656,
            longitude: 135.4324,
            rating: 4.5,
            tips: '익스프레스 패스 구매하면 대기 시간 크게 단축. 사전 구매 필수.',
          },
        ],
      },
    ],
    foods: [
      { name: '타코야키', nameLocal: 'たこ焼き', description: '오사카의 소울 푸드. 바삭한 겉면과 트로트로한 속. 길거리 간식의 왕.', priceRange: '500~800엔', mustTry: true, bestSpots: ['와나카', '쿠쿠루', '아카시야키'], mealType: 'snack' },
      { name: '오코노미야키', nameLocal: 'お好み焼き', description: '오사카식은 재료를 섞어 굽는 스타일. 마요+소스 조합이 핵심.', priceRange: '800~1,500엔', mustTry: true, bestSpots: ['미즈노', '후쿠타로', '치보'], mealType: 'lunch' },
      { name: '쿠시카츠', nameLocal: '串カツ', description: '재료를 꼬치에 끼워 튀기는 신세카이 명물. 소스 이중 딥 금지!', priceRange: '1,000~2,000엔', mustTry: true, bestSpots: ['다루마', '요시다'], mealType: 'dinner' },
      { name: '이카야키', nameLocal: 'いか焼き', description: '오징어를 반죽에 넣어 철판에 눌러 구운 오사카 서민 간식.', priceRange: '200~400엔', mustTry: false, bestSpots: ['한큐 백화점 지하'], mealType: 'snack' },
      { name: '551 호라이 부타만', nameLocal: '551蓬莱豚まん', description: '오사카 기차역 명물 돼지고기 만두. 오사카인의 소울 간식.', priceRange: '200~400엔', mustTry: true, bestSpots: ['난바 본점', '각 역사 매장'], mealType: 'snack' },
    ],
    events: [
      { name: '텐진마츠리', nameLocal: '天神祭', period: '7월 24~25일', description: '일본 3대 축제. 배 퍼레이드와 불꽃놀이.', highlight: '오카와 강 위 불꽃놀이와 배 행렬' },
      { name: '에비스마츠리', nameLocal: '十日戎', period: '1월 9~11일', description: '이마미야 에비스 신사의 상매 번영 축제.', highlight: '복 갈퀴(후쿠자사)를 사서 한 해 운을 기원' },
    ],
    transportLinks: [
      { from: '도쿄', method: '신칸센 노조미', duration: '약 2시간 15분', cost: '14,720엔', tips: '신오사카역 하차 후 미도스지선으로 난바까지 15분' },
      { from: '오사카', method: '-', duration: '-', cost: '-' },
    ],
    neighborCities: [
      { cityId: 'kyoto', cityName: '교토', transport: 'JR/한큐', duration: '약 15~30분', dayTripViable: true },
      { cityId: 'nara', cityName: '나라', transport: '긴테쓰', duration: '약 35분', dayTripViable: true },
      { cityId: 'kobe', cityName: '고베', transport: 'JR', duration: '약 21분', dayTripViable: true },
    ],
    travelTips: [
      '오사카 주유패스(1일 2,800엔)로 40개+ 시설 무료 입장 + 전철 무제한',
      '"쿠이다오레"(食い倒れ): 먹다 쓰러지는 것이 오사카 여행의 정수',
      '에스컬레이터는 오른쪽에 서세요 (도쿄와 반대)',
      '난바·신사이바시 근처 숙소가 접근성 최고',
      '교토·나라 당일치기가 쉬워서 오사카를 베이스캠프로 추천',
    ],
    tags: ['미식', '타코야키', 'USJ', '쇼핑', '야경', '서민문화', '가족여행'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // KYOTO (京都)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'kyoto',
    name: '교토',
    nameLocal: '京都',
    country: '일본',
    region: '간사이',
    description: '천년 고도. 17개 세계유산, 2,000개 이상의 신사와 사찰의 도시.',
    character: '시간이 멈춘 듯한 일본 전통 미의 정수',
    bestSeasons: ['spring', 'autumn'],
    averageStay: '2~4일',
    budgetPerDay: { economy: '8,000~12,000엔', mid: '15,000~25,000엔', premium: '40,000엔~' },
    areas: [
      {
        name: '히가시야마',
        nameLocal: '東山',
        description: '기요미즈데라, 기온, 니넨자카를 잇는 교토의 황금 루트.',
        walkable: true,
        timeNeeded: '4~6시간',
        places: [
          {
            name: '기요미즈데라',
            nameLocal: '清水寺',
            category: '신사/사찰',
            description: '교토의 상징. "기요미즈의 무대"에서 내려다보는 절경. 세계유산.',
            mustVisit: true,
            hours: '06:00~18:00 (야간 특별 관람 시즌별)',
            admission: '400엔',
            duration: '1~1.5시간',
            latitude: 35.0050,
            longitude: 135.7851,
            rating: 4.6,
            tips: '봄·가을 야간 특별 관람(라이트업)이 환상적이에요.',
          },
          {
            name: '니넨자카·산넨자카',
            nameLocal: '二年坂・三年坂',
            category: '관광지',
            description: '기요미즈데라로 이어지는 돌계단 골목. 전통 상점과 카페.',
            mustVisit: true,
            hours: '상시 (가게 09:00~18:00)',
            admission: '무료',
            duration: '30분~1시간',
            latitude: 35.0019,
            longitude: 135.7808,
            rating: 4.5,
            tips: '스타벅스 니넨자카점은 전통 가옥을 개조한 유니크한 매장.',
          },
          {
            name: '기온 (하나미코지)',
            nameLocal: '祇園・花見小路',
            category: '관광지',
            description: '마이코(게이샤)를 만날 수 있는 전통 거리. 석등과 목조 건물.',
            mustVisit: true,
            hours: '상시',
            admission: '무료',
            duration: '1시간',
            latitude: 35.0037,
            longitude: 135.7749,
            rating: 4.4,
            tips: '저녁에 방문하면 마이코를 볼 확률이 높아요. 사진 촬영 매너 주의.',
          },
        ],
      },
      {
        name: '킨카쿠지·아라시야마',
        nameLocal: '金閣寺・嵐山',
        description: '금각사의 화려함과 아라시야마 대나무숲의 청량함.',
        walkable: false,
        timeNeeded: '4~5시간',
        places: [
          {
            name: '킨카쿠지 (금각사)',
            nameLocal: '金閣寺',
            category: '신사/사찰',
            description: '금박으로 덮인 누각이 호수에 비치는 절경. 세계유산.',
            mustVisit: true,
            hours: '09:00~17:00',
            admission: '500엔',
            duration: '45분~1시간',
            latitude: 35.0394,
            longitude: 135.7292,
            rating: 4.6,
            tips: '오전에 방문하면 금각이 햇빛에 반짝이며 사진이 잘 나와요.',
          },
          {
            name: '아라시야마 대나무숲',
            nameLocal: '嵐山竹林の小径',
            category: '자연',
            description: '하늘 높이 솟은 대나무가 만드는 초록색 터널. 교토의 힐링 스팟.',
            mustVisit: true,
            hours: '상시',
            admission: '무료',
            duration: '30분~1시간',
            latitude: 35.0170,
            longitude: 135.6713,
            rating: 4.5,
            tips: '아침 7시 전에 방문하면 인파 없이 몽환적 사진 가능.',
          },
          {
            name: '도게츠교',
            nameLocal: '渡月橋',
            category: '관광지',
            description: '아라시야마의 상징적 다리. 산과 강이 어우러진 풍경.',
            mustVisit: true,
            hours: '상시',
            admission: '무료',
            duration: '20분',
            latitude: 35.0116,
            longitude: 135.6780,
            rating: 4.3,
          },
        ],
      },
      {
        name: '후시미',
        nameLocal: '伏見',
        description: '천 개의 도리이로 유명한 후시미이나리 신사와 사케의 고장.',
        walkable: true,
        timeNeeded: '2~3시간',
        places: [
          {
            name: '후시미이나리 대사',
            nameLocal: '伏見稲荷大社',
            category: '신사/사찰',
            description: '천 본의 붉은 도리이가 산을 오르는 장관. 교토 No.1 명소.',
            mustVisit: true,
            hours: '상시 개방',
            admission: '무료',
            duration: '1.5~3시간 (정상까지)',
            latitude: 35.0337,
            longitude: 135.7727,
            rating: 4.7,
            tips: '정상까지 왕복 약 2시간. 중간 미츠츠지에서 돌아와도 충분해요.',
          },
        ],
      },
    ],
    foods: [
      { name: '유도후 (두부 요리)', nameLocal: '湯豆腐', description: '교토 사찰 음식의 대표. 담백하고 깊은 맛의 두부 요리.', priceRange: '1,500~3,500엔', mustTry: true, bestSpots: ['난젠지 준세이', '오카쿠'], mealType: 'lunch' },
      { name: '교 가이세키', nameLocal: '京懐石', description: '교토식 코스 요리. 제철 식재료를 예술적으로 담아낸 일본 요리의 정수.', priceRange: '8,000~30,000엔', mustTry: true, bestSpots: ['기온 마루야마', '요시히로'], mealType: 'dinner' },
      { name: '마차 디저트', nameLocal: '抹茶スイーツ', description: '우지 말차를 사용한 파르페, 티라미수, 아이스크림 등.', priceRange: '500~1,500엔', mustTry: true, bestSpots: ['나카무라 토키치', '쓰지리'], mealType: 'snack' },
      { name: '니신소바 (청어 소바)', nameLocal: 'にしんそば', description: '달짝한 청어 조림을 올린 교토 전통 소바.', priceRange: '1,000~1,500엔', mustTry: false, bestSpots: ['마츠바'], mealType: 'lunch' },
      { name: '야츠하시', nameLocal: '八ツ橋', description: '교토 대표 기념품. 쌀가루·계피·팥소로 만든 삼각형 과자.', priceRange: '500~1,000엔', mustTry: false, bestSpots: ['기온 각 기념품점'], mealType: 'snack' },
    ],
    events: [
      { name: '기온 마츠리', nameLocal: '祇園祭', period: '7월 (하이라이트 17·24일)', description: '일본 3대 축제. 거대한 야마보코(수레)가 시내를 행진.', highlight: '17일 야마보코 순행이 최대 볼거리' },
      { name: '단풍 라이트업', nameLocal: '紅葉ライトアップ', period: '11월 중순~12월 초', description: '에이칸도, 기요미즈데라 등 야간 단풍 조명.', highlight: '에이칸도의 단풍 반사 연못이 최고' },
      { name: '하나토로', nameLocal: '花灯路', period: '3월·12월', description: '아라시야마·히가시야마 골목에 등불을 켜는 환상적 이벤트.', highlight: '대나무숲 라이트업' },
    ],
    transportLinks: [
      { from: '도쿄', method: '신칸센 노조미', duration: '약 2시간 10분', cost: '14,170엔' },
      { from: '오사카', method: 'JR/한큐/게이한', duration: '약 15~50분', cost: '410~920엔' },
    ],
    neighborCities: [
      { cityId: 'osaka', cityName: '오사카', transport: 'JR/한큐', duration: '약 15~30분', dayTripViable: true },
      { cityId: 'nara', cityName: '나라', transport: '긴테쓰', duration: '약 45분', dayTripViable: true },
      { cityId: 'uji', cityName: '우지', transport: 'JR/게이한', duration: '약 20분', dayTripViable: true },
    ],
    travelTips: [
      '버스 1일권(700엔)으로 주요 관광지 이동 가능하지만 혼잡 주의',
      '봄(3~4월)·가을(11월) 성수기에는 숙소 2~3개월 전 예약 필수',
      '기모노 렌탈(3,000~5,000엔)하고 히가시야마 산책이 인기 코스',
      '자전거 렌탈(1일 1,000엔)이 교토 여행의 베스트 교통수단',
      '관광지는 오전 일찍 방문해야 쾌적해요 (특히 후시미이나리, 아라시야마)',
    ],
    tags: ['전통', '세계유산', '사찰', '마차', '기모노', '벚꽃', '단풍', '가이세키'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // FUKUOKA (福岡)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'fukuoka',
    name: '후쿠오카',
    nameLocal: '福岡',
    country: '일본',
    region: '규슈',
    description: '규슈의 관문. 돈코츠 라멘, 야타이, 모츠나베의 미식 도시.',
    character: '먹고 놀기 좋은 콤팩트한 미식 도시',
    bestSeasons: ['spring', 'autumn'],
    averageStay: '2~3일',
    budgetPerDay: { economy: '7,000~10,000엔', mid: '12,000~20,000엔', premium: '25,000엔~' },
    areas: [
      {
        name: '나카스·텐진',
        nameLocal: '中洲・天神',
        description: '후쿠오카 최대 번화가. 야타이(포장마차) 거리와 쇼핑의 중심.',
        walkable: true,
        timeNeeded: '3~4시간',
        places: [
          {
            name: '나카스 야타이 거리',
            nameLocal: '中洲屋台街',
            category: '맛집',
            description: '강변에 늘어선 포장마차. 라멘, 오뎅, 교자 등을 현지인과 어깨 맞대고.',
            mustVisit: true,
            hours: '18:00~02:00',
            duration: '1~2시간',
            latitude: 33.5921,
            longitude: 130.4028,
            rating: 4.4,
            tips: '금·토요일은 줄이 길어요. 평일 저녁이 쾌적.',
          },
          {
            name: '캐널시티 하카타',
            nameLocal: 'キャナルシティ博多',
            category: '쇼핑',
            description: '운하가 흐르는 대형 복합시설. 라멘 스타디움(8층)이 유명.',
            mustVisit: true,
            hours: '10:00~21:00',
            duration: '1.5~2시간',
            latitude: 33.5898,
            longitude: 130.4110,
            rating: 4.1,
          },
          {
            name: '텐진 지하상가',
            nameLocal: '天神地下街',
            category: '쇼핑',
            description: '유럽풍 인테리어의 일본 최대급 지하상가. 150개+ 매장.',
            mustVisit: false,
            hours: '10:00~20:00',
            duration: '1시간',
            latitude: 33.5897,
            longitude: 130.3991,
            rating: 4.0,
          },
        ],
      },
      {
        name: '하카타역·구시다 신사',
        nameLocal: '博多駅・櫛田神社',
        description: '후쿠오카의 현관. 역사적 신사와 현대적 역세권.',
        walkable: true,
        timeNeeded: '2~3시간',
        places: [
          {
            name: '구시다 신사',
            nameLocal: '櫛田神社',
            category: '신사/사찰',
            description: '하카타의 수호신사. 하카타 기온 야마카사 축제의 중심.',
            mustVisit: true,
            hours: '04:00~22:00',
            admission: '무료',
            duration: '30분',
            latitude: 33.5912,
            longitude: 130.4089,
            rating: 4.3,
            tips: '경내에 전시된 야마카사 장식수레가 볼만해요.',
          },
          {
            name: '하카타 마치야 민속관',
            nameLocal: '博多町家ふるさと館',
            category: '관광지',
            description: '하카타 전통 문화와 공예를 체험할 수 있는 소규모 박물관.',
            mustVisit: false,
            hours: '10:00~18:00',
            admission: '200엔',
            duration: '30분~1시간',
            latitude: 33.5911,
            longitude: 130.4079,
            rating: 4.0,
          },
        ],
      },
      {
        name: '오호리 공원·후쿠오카성',
        nameLocal: '大濠公園・福岡城',
        description: '시민의 휴식처. 호수 산책, 벚꽃 명소, 성터.',
        walkable: true,
        timeNeeded: '1.5~2시간',
        places: [
          {
            name: '오호리 공원',
            nameLocal: '大濠公園',
            category: '자연',
            description: '호수를 중심으로 한 아름다운 시민공원. 조깅, 보트, 산책.',
            mustVisit: false,
            hours: '상시',
            admission: '무료',
            duration: '1시간',
            latitude: 33.5868,
            longitude: 130.3792,
            rating: 4.3,
          },
        ],
      },
    ],
    foods: [
      { name: '하카타 돈코츠 라멘', nameLocal: '博多豚骨ラーメン', description: '유백색 돈코츠 스프에 가는 면. 카에다마(면 추가)는 필수.', priceRange: '700~1,000엔', mustTry: true, bestSpots: ['잇푸도', '이치란', '신신', '나가하마 야타이'], mealType: 'any' },
      { name: '모츠나베', nameLocal: 'もつ鍋', description: '소 곱창을 니라·양배추와 함께 끓인 후쿠오카 향토 냄비.', priceRange: '1,500~3,000엔', mustTry: true, bestSpots: ['야마모토야', '오오야마'], mealType: 'dinner' },
      { name: '하카타 교자', nameLocal: '博多餃子', description: '한 입 사이즈의 작은 만두. 바삭한 겉면과 육즙이 포인트.', priceRange: '300~600엔', mustTry: true, bestSpots: ['텐츠 교자', '야타이'], mealType: 'any' },
      { name: '미즈타키', nameLocal: '水炊き', description: '닭고기를 맑은 육수에 끓인 교토풍 나베. 후쿠오카의 또다른 명물.', priceRange: '2,000~4,000엔', mustTry: false, bestSpots: ['하카타 하나미도리'], mealType: 'dinner' },
      { name: '멘타이코', nameLocal: '明太子', description: '매콤한 명란젓. 밥 반찬, 파스타, 빵 등 다양하게 응용.', priceRange: '500~2,000엔', mustTry: true, bestSpots: ['후쿠야', '카네후쿠 멘타이코 파크'], mealType: 'any' },
    ],
    events: [
      { name: '하카타 기온 야마카사', nameLocal: '博多祇園山笠', period: '7월 1~15일', description: '700년 역사의 하카타 대표 축제. 1톤짜리 수레를 메고 달림.', highlight: '15일 새벽 오이야마(追い山)가 최대 클라이맥스' },
      { name: '하카타 돈타쿠', nameLocal: '博多どんたく', period: '5월 3~4일', description: '200만 명이 참가하는 시민 축제.', highlight: '시민 퍼레이드와 거리 공연' },
    ],
    transportLinks: [
      { from: '도쿄', method: '비행기', duration: '약 1시간 50분', cost: '8,000~25,000엔', tips: '후쿠오카 공항에서 지하철로 하카타역 5분, 텐진 11분' },
      { from: '오사카', method: '신칸센 미즈호', duration: '약 2시간 15분', cost: '15,600엔' },
    ],
    neighborCities: [
      { cityId: 'dazaifu', cityName: '다자이후', transport: '니시테츠', duration: '약 30분', dayTripViable: true },
      { cityId: 'beppu', cityName: '벳푸', transport: 'JR 소닉', duration: '약 2시간', dayTripViable: true },
      { cityId: 'nagasaki', cityName: '나가사키', transport: '니시큐슈 신칸센', duration: '약 1시간 20분', dayTripViable: true },
    ],
    travelTips: [
      '후쿠오카 공항 접근성이 일본 최고 (지하철로 하카타역 5분)',
      '야타이는 비가 오면 영업 안 하는 곳이 많으니 날씨 확인',
      '라멘은 면 굳기를 선택 가능: 바리카타(매우 딱딱) > 카타(딱딱) > 후츠(보통)',
      '니시테츠 버스 1일권(900엔)으로 시내 이동 편리',
      '쇼핑은 텐진, 먹거리는 나카스, 역사는 하카타역 주변으로 나뉨',
    ],
    tags: ['라멘', '야타이', '미식', '공항접근성', '규슈', '모츠나베', '멘타이코'],
  },
];
