import { CityProfile } from './types';

// ─── Southeast Asia City Data ─────────────────────────────

export const SEA_CITIES: CityProfile[] = [
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // BANGKOK (กรุงเทพ)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'bangkok',
    name: '방콕',
    nameLocal: 'กรุงเทพ',
    country: '태국',
    region: '동남아시아',
    description: '왕궁과 사원, 야시장과 루프탑 바가 공존하는 동남아 최대 도시. 저렴한 물가와 풍부한 먹거리의 천국.',
    character: '혼돈 속 매력, 먹거리와 사원의 도시',
    bestSeasons: ['winter'],
    averageStay: '3~5일',
    budgetPerDay: { economy: '30,000~50,000원', mid: '80,000~150,000원', premium: '200,000원~' },
    areas: [
      {
        name: '왕궁·왓포 지구',
        nameLocal: 'เขตพระนคร',
        description: '방콕의 역사 중심지. 왕궁, 왓포, 왓아룬 등 핵심 사원이 밀집.',
        walkable: true,
        timeNeeded: '4~5시간',
        places: [
          {
            name: '왕궁 (그랜드 팰리스)',
            nameLocal: 'พระบรมมหาราชวัง',
            category: '관광지',
            description: '태국 왕실의 공식 거주지. 에메랄드 불상이 모셔진 왓 프라깨우가 내부에 위치.',
            mustVisit: true,
            hours: '08:30~15:30',
            admission: '500바트',
            duration: '2~3시간',
            latitude: 13.7510,
            longitude: 100.4914,
            rating: 4.6,
            tips: '반바지·민소매 입장 불가. 긴 옷 준비 필수.',
          },
          {
            name: '왓포 (와불 사원)',
            nameLocal: 'วัดโพธิ์',
            category: '관광지',
            description: '46m 길이의 거대한 와불상으로 유명. 타이 마사지 발상지이기도.',
            mustVisit: true,
            hours: '08:00~18:30',
            admission: '200바트',
            duration: '1~1.5시간',
            latitude: 13.7465,
            longitude: 100.4930,
            rating: 4.5,
          },
          {
            name: '왓아룬 (새벽 사원)',
            nameLocal: 'วัดอรุณ',
            category: '관광지',
            description: '짜오프라야 강변의 아이코닉한 사원. 석양에 특히 아름다움.',
            mustVisit: true,
            hours: '08:00~18:00',
            admission: '100바트',
            duration: '1시간',
            latitude: 13.7437,
            longitude: 100.4888,
            rating: 4.5,
            tips: '왓포에서 배(4바트)로 건너갈 수 있어요.',
          },
        ],
      },
      {
        name: '카오산 로드·민주기념탑',
        nameLocal: 'ถนนข้าวสาร',
        description: '배낭여행자의 성지. 저렴한 숙소, 길거리 음식, 밤문화.',
        walkable: true,
        timeNeeded: '2~3시간',
        places: [
          {
            name: '카오산 로드',
            nameLocal: 'ถนนข้าวสาร',
            category: '쇼핑',
            description: '세계 배낭여행자의 메카. 길거리 음식, 마사지, 바가 즐비.',
            mustVisit: true,
            hours: '상시 (밤이 메인)',
            duration: '2~3시간',
            latitude: 13.7588,
            longitude: 100.4974,
            rating: 4.2,
          },
        ],
      },
      {
        name: '수쿰빗·시암',
        nameLocal: 'สุขุมวิท・สยาม',
        description: '현대적 쇼핑몰, 루프탑 바, 고급 레스토랑이 모인 방콕의 모던 지구.',
        walkable: true,
        timeNeeded: '3~4시간',
        places: [
          {
            name: '시암 파라곤',
            nameLocal: 'สยามพารากอน',
            category: '쇼핑',
            description: '방콕 최고급 쇼핑몰. 지하에 아쿠아리움도 있음.',
            mustVisit: false,
            hours: '10:00~22:00',
            duration: '2~3시간',
            latitude: 13.7466,
            longitude: 100.5347,
            rating: 4.4,
          },
          {
            name: '짜뚜짝 주말시장',
            nameLocal: 'ตลาดนัดจตุจักร',
            category: '쇼핑',
            description: '15,000개 이상의 부스가 모인 세계 최대 규모 주말시장.',
            mustVisit: true,
            hours: '토·일 09:00~18:00',
            duration: '3~4시간',
            latitude: 13.7999,
            longitude: 100.5506,
            rating: 4.4,
            tips: '더위가 심하니 오전에 방문 추천. BTS 모칫역 하차.',
          },
        ],
      },
    ],
    foods: [
      { name: '팟타이', nameLocal: 'ผัดไทย', description: '새우와 숙주, 땅콩을 볶은 태국 대표 볶음 국수.', priceRange: '50~150바트', mustTry: true, bestSpots: ['팁 사마이', '카오산 로드 노점'], mealType: 'any' },
      { name: '똠양꿍', nameLocal: 'ต้มยำกุ้ง', description: '새우가 들어간 매콤·시큼한 태국 대표 수프.', priceRange: '100~300바트', mustTry: true, bestSpots: ['페 끄룽 카오', '쏨분 씨푸드'], mealType: 'lunch' },
      { name: '카오 팟 (볶음밥)', nameLocal: 'ข้าวผัด', description: '태국식 볶음밥. 게, 새우, 돼지고기 등 다양한 버전.', priceRange: '50~120바트', mustTry: false, bestSpots: ['길거리 노점', '푸드코트'], mealType: 'any' },
      { name: '망고 스티키 라이스', nameLocal: 'ข้าวเหนียวมะม่วง', description: '달콤한 코코넛 찹쌀밥과 신선한 망고 조합. 태국 디저트의 정수.', priceRange: '80~150바트', mustTry: true, bestSpots: ['매 와리', '짜뚜짝 시장'], mealType: 'snack' },
    ],
    events: [
      { name: '송끄란 (물 축제)', nameLocal: 'สงกรานต์', period: '4월 13~15일', description: '태국 새해 물 축제. 거리에서 물을 뿌리며 축하.', highlight: '카오산 로드와 시암 일대가 거대한 물싸움 장소로 변신' },
      { name: '러이 끄라통', nameLocal: 'ลอยกระทง', period: '11월 보름', description: '물 위에 연꽃 모양 등불을 띄우는 전통 축제.', highlight: '짜오프라야 강에 수천 개의 등불이 떠다니는 환상적 풍경' },
    ],
    transportLinks: [
      { from: '인천', method: '직항', duration: '약 5시간 30분', cost: '200,000~500,000원' },
      { from: '수완나품 공항→시내', method: '에어포트 레일 링크', duration: '약 30분', cost: '45바트' },
    ],
    neighborCities: [
      { cityId: 'ayutthaya', cityName: '아유타야', transport: '기차/미니밴', duration: '약 1시간 30분', dayTripViable: true },
      { cityId: 'pattaya', cityName: '파타야', transport: '버스', duration: '약 2시간', dayTripViable: true },
    ],
    travelTips: [
      'BTS(스카이트레인)·MRT(지하철)로 주요 관광지 이동 편리',
      '택시는 반드시 미터기 사용 요청. 그랩(Grab) 앱 추천',
      '사원 방문 시 어깨·무릎을 가리는 복장 필수',
      '길거리 음식은 현지인이 많은 곳이 맛있고 안전',
      '11~2월 건기가 여행 최적기, 4~5월은 극심한 더위',
    ],
    tags: ['사원', '야시장', '미식', '쇼핑', '배낭여행', '루프탑바'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // BALI (บาหลี)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'bali',
    name: '발리',
    nameLocal: 'Bali',
    country: '인도네시아',
    region: '동남아시아',
    description: '힌두 사원, 계단식 논, 서핑 해변이 어우러진 인도네시아의 보석. 요가와 힐링의 성지.',
    character: '자연과 영성이 만나는 열대 낙원',
    bestSeasons: ['spring', 'summer'],
    averageStay: '5~7일',
    budgetPerDay: { economy: '40,000~60,000원', mid: '100,000~200,000원', premium: '300,000원~' },
    areas: [
      {
        name: '우붓',
        nameLocal: 'Ubud',
        description: '발리의 문화 수도. 예술, 요가, 계단식 논(라이스 테라스)의 중심지.',
        walkable: false,
        timeNeeded: '1~2일',
        places: [
          {
            name: '뜨갈랄랑 라이스 테라스',
            nameLocal: 'Tegallalang Rice Terrace',
            category: '자연',
            description: '인스타그램에서 유명한 계단식 논. 정글 스윙도 체험 가능.',
            mustVisit: true,
            hours: '08:00~18:00',
            admission: '15,000루피아',
            duration: '1~2시간',
            latitude: -8.4312,
            longitude: 115.2792,
            rating: 4.5,
            tips: '오전 일찍 방문하면 붐비지 않고 빛이 예뻐요.',
          },
          {
            name: '우붓 몽키 포레스트',
            nameLocal: 'Sacred Monkey Forest Sanctuary',
            category: '자연',
            description: '700마리 이상의 원숭이가 사는 신성한 숲. 사원과 거대한 나무들.',
            mustVisit: true,
            hours: '08:30~18:00',
            admission: '80,000루피아',
            duration: '1~1.5시간',
            latitude: -8.5185,
            longitude: 115.2586,
            rating: 4.4,
            tips: '선글라스·모자 등 원숭이가 뺏어갈 수 있는 물건 주의.',
          },
        ],
      },
      {
        name: '스미냑·꾸따',
        nameLocal: 'Seminyak & Kuta',
        description: '해변, 서핑, 비치 클럽, 쇼핑이 어우러진 발리 남부의 활기찬 지역.',
        walkable: false,
        timeNeeded: '1~2일',
        places: [
          {
            name: '꾸따 비치',
            nameLocal: 'Kuta Beach',
            category: '비치',
            description: '발리에서 가장 유명한 해변. 서핑 입문자에게 완벽한 파도.',
            mustVisit: true,
            hours: '상시',
            duration: '2~3시간',
            latitude: -8.7184,
            longitude: 115.1686,
            rating: 4.2,
          },
          {
            name: '포테이토 헤드 비치 클럽',
            nameLocal: 'Potato Head Beach Club',
            category: '카페',
            description: '스미냑의 아이코닉한 비치 클럽. 선셋 감상 명소.',
            mustVisit: true,
            hours: '10:00~02:00',
            duration: '3~4시간',
            latitude: -8.6857,
            longitude: 115.1550,
            rating: 4.5,
            tips: '선셋 타임 자리 확보를 위해 16시쯤 도착 추천.',
          },
        ],
      },
      {
        name: '울루와뚜',
        nameLocal: 'Uluwatu',
        description: '절벽 위 사원과 서핑 포인트, 럭셔리 리조트가 모인 남부 해안.',
        walkable: false,
        timeNeeded: '반나절',
        places: [
          {
            name: '울루와뚜 사원',
            nameLocal: 'Pura Luhur Uluwatu',
            category: '관광지',
            description: '70m 절벽 위에 세워진 바다 사원. 일몰 시 케착 댄스 공연이 유명.',
            mustVisit: true,
            hours: '07:00~19:00',
            admission: '50,000루피아',
            duration: '2시간',
            latitude: -8.8291,
            longitude: 115.0849,
            rating: 4.6,
            tips: '케착 댄스(18:00)는 사전 예약 추천. 원숭이 주의.',
          },
        ],
      },
    ],
    foods: [
      { name: '나시고렝', nameLocal: 'Nasi Goreng', description: '인도네시아식 볶음밥. 계란 프라이와 새우 크래커를 곁들임.', priceRange: '25,000~60,000루피아', mustTry: true, bestSpots: ['와룽(현지 식당)', '우붓 시장'], mealType: 'any' },
      { name: '바비 굴링 (통돼지 구이)', nameLocal: 'Babi Guling', description: '발리 힌두교 축제 음식이 일상화된 통돼지 바비큐.', priceRange: '50,000~80,000루피아', mustTry: true, bestSpots: ['이부 오카', '빠 바구스'], mealType: 'lunch' },
      { name: '미고렝', nameLocal: 'Mie Goreng', description: '인도네시아식 볶음 국수. 달콤한 간장 소스가 특징.', priceRange: '20,000~50,000루피아', mustTry: false, bestSpots: ['와룽 현지 식당'], mealType: 'any' },
    ],
    events: [
      { name: '뉴피 (침묵의 날)', nameLocal: 'Nyepi', period: '3월 (발리 새해)', description: '24시간 동안 섬 전체가 멈추는 침묵의 날. 공항도 폐쇄.', highlight: '전날 밤 오고오고(거대 인형) 퍼레이드가 장관' },
      { name: '갈루간', nameLocal: 'Galungan', period: '210일 주기', description: '선과 악의 승리를 기념하는 발리 최대 힌두 축제.', highlight: '집집마다 대나무 장식(펜조르)을 세우는 아름다운 풍경' },
    ],
    transportLinks: [
      { from: '인천', method: '직항', duration: '약 7시간', cost: '300,000~700,000원' },
      { from: '응우라라이 공항→우붓', method: '택시/그랩', duration: '약 1시간 30분', cost: '250,000~350,000루피아' },
    ],
    neighborCities: [
      { cityId: 'nusapenida', cityName: '누사 페니다', transport: '스피드보트', duration: '약 30분', dayTripViable: true },
      { cityId: 'gili', cityName: '길리 섬', transport: '스피드보트', duration: '약 1시간 30분', dayTripViable: false },
    ],
    travelTips: [
      '그랩(Grab) 또는 고젝(GoJek) 앱으로 이동이 가장 편리',
      '스쿠터 렌트 시 국제운전면허증 필수 (경찰 단속 잦음)',
      '사원 방문 시 사롱(천) 착용 필수 (대여 가능)',
      '우기(11~3월)에도 오전은 맑은 경우가 많아 여행 가능',
      '팁 문화 있음. 식당 5~10%, 마사지사 20,000~50,000루피아',
    ],
    tags: ['해변', '서핑', '요가', '사원', '라이스테라스', '힐링', '비치클럽'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // DA NANG (Đà Nẵng)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'danang',
    name: '다낭',
    nameLocal: 'Đà Nẵng',
    country: '베트남',
    region: '동남아시아',
    description: '아름다운 해변과 바나힐, 호이안·후에 접근성이 좋은 베트남 중부 거점 도시.',
    character: '해변과 역사가 공존하는 베트남의 리조트 시티',
    bestSeasons: ['spring', 'summer'],
    averageStay: '3~5일',
    budgetPerDay: { economy: '30,000~50,000원', mid: '80,000~150,000원', premium: '200,000원~' },
    areas: [
      {
        name: '미케 비치·한강',
        nameLocal: 'Bãi biển Mỹ Khê',
        description: '미케 비치는 포브스 선정 세계 6대 해변. 한강 다리의 야경도 필수.',
        walkable: true,
        timeNeeded: '반나절',
        places: [
          {
            name: '미케 비치',
            nameLocal: 'Bãi biển Mỹ Khê',
            category: '비치',
            description: '다낭 시내에서 가장 접근성 좋은 화이트 샌드 비치. 서핑과 수영에 좋음.',
            mustVisit: true,
            hours: '상시',
            duration: '2~3시간',
            latitude: 16.0544,
            longitude: 108.2472,
            rating: 4.5,
          },
          {
            name: '용 다리 (드래곤 브릿지)',
            nameLocal: 'Cầu Rồng',
            category: '관광지',
            description: '용 형태의 다리. 주말 밤 9시 불과 물을 뿜는 쇼가 명물.',
            mustVisit: true,
            hours: '상시 (쇼: 토·일 21:00)',
            duration: '30분',
            latitude: 16.0610,
            longitude: 108.2270,
            rating: 4.3,
          },
        ],
      },
      {
        name: '바나힐',
        nameLocal: 'Bà Nà Hills',
        description: '해발 1,400m의 테마파크. 골든 브릿지(손 다리)가 세계적으로 유명.',
        walkable: true,
        timeNeeded: '1일',
        places: [
          {
            name: '바나힐·골든 브릿지',
            nameLocal: 'Cầu Vàng, Bà Nà Hills',
            category: '관광지',
            description: '거대한 돌 손이 받치는 황금빛 다리. 세계에서 가장 인스타그래머블한 다리.',
            mustVisit: true,
            hours: '07:00~22:00',
            admission: '900,000동 (케이블카 포함)',
            duration: '5~6시간',
            latitude: 15.9950,
            longitude: 107.9964,
            rating: 4.4,
            tips: '오전 일찍 가면 안개 속 골든 브릿지를 볼 수 있어요.',
          },
        ],
      },
      {
        name: '호이안 (근교)',
        nameLocal: 'Hội An',
        description: '다낭에서 30분 거리의 유네스코 세계문화유산 고대 도시.',
        walkable: true,
        timeNeeded: '반나절~1일',
        places: [
          {
            name: '호이안 올드타운',
            nameLocal: 'Phố cổ Hội An',
            category: '관광지',
            description: '등불로 물드는 아름다운 고대 도시. 맞춤 옷 제작과 현지 음식이 유명.',
            mustVisit: true,
            hours: '상시 (등불은 일몰 후)',
            admission: '120,000동 (올드타운 패스)',
            duration: '4~5시간',
            latitude: 15.8801,
            longitude: 108.3380,
            rating: 4.7,
            tips: '매달 음력 14일 랜턴 축제 때 가장 아름다워요.',
          },
        ],
      },
    ],
    foods: [
      { name: '반미', nameLocal: 'Bánh Mì', description: '프랑스 바게트에 베트남 재료를 넣은 세계적 샌드위치.', priceRange: '20,000~40,000동', mustTry: true, bestSpots: ['반미 바 (Bánh Mì Bà)', '마담 란'], mealType: 'any' },
      { name: '분짜', nameLocal: 'Bún Chả', description: '구운 돼지고기와 쌀국수를 느억맘 소스에 찍어 먹는 하노이식 요리.', priceRange: '40,000~70,000동', mustTry: true, bestSpots: ['콤탐 바오 (현지 식당)'], mealType: 'lunch' },
      { name: '까오러우', nameLocal: 'Cao Lầu', description: '호이안 전통 면 요리. 쫄깃한 면에 돼지고기와 허브를 얹음.', priceRange: '30,000~50,000동', mustTry: true, bestSpots: ['호이안 중앙시장', '미스 리'], mealType: 'lunch' },
      { name: '쩨 (베트남 디저트)', nameLocal: 'Chè', description: '코코넛 밀크 베이스의 달콤한 베트남 전통 디저트.', priceRange: '15,000~30,000동', mustTry: false, bestSpots: ['한시장 근처 노점'], mealType: 'snack' },
    ],
    events: [
      { name: '호이안 랜턴 축제', nameLocal: 'Hội An Lantern Festival', period: '매달 음력 14일', description: '호이안 올드타운이 수천 개의 등불로 물드는 야간 축제.', highlight: '투본강에 소원 등불을 띄우는 낭만적 체험' },
    ],
    transportLinks: [
      { from: '인천', method: '직항', duration: '약 4시간 30분', cost: '150,000~400,000원' },
      { from: '다낭 공항→시내', method: '택시/그랩', duration: '약 15분', cost: '100,000~150,000동' },
    ],
    neighborCities: [
      { cityId: 'hoian', cityName: '호이안', transport: '택시/버스', duration: '약 30분', dayTripViable: true },
      { cityId: 'hue', cityName: '후에', transport: '기차/버스', duration: '약 2시간 30분', dayTripViable: true },
    ],
    travelTips: [
      '그랩(Grab) 앱이 택시보다 안전하고 저렴',
      '9~12월은 우기로 태풍 가능성. 1~8월 추천',
      '호이안은 다낭에서 차로 30분, 반일 이상 투자할 가치',
      '해산물은 미케 비치 남쪽 해산물 거리에서 저렴하게',
      '오토바이 렌트 비용 하루 약 100,000~150,000동',
    ],
    tags: ['해변', '골든브릿지', '호이안', '미식', '리조트', '가성비'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // SINGAPORE (新加坡)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'singapore',
    name: '싱가포르',
    nameLocal: 'Singapore',
    country: '싱가포르',
    region: '동남아시아',
    description: '깨끗하고 안전한 다문화 도시국가. 미식, 쇼핑, 미래형 건축이 공존하는 동남아의 보석.',
    character: '깨끗한 도시에 담긴 다문화 미식 천국',
    bestSeasons: ['spring', 'winter'],
    averageStay: '3~4일',
    budgetPerDay: { economy: '80,000~120,000원', mid: '150,000~250,000원', premium: '400,000원~' },
    areas: [
      {
        name: '마리나 베이',
        nameLocal: 'Marina Bay',
        description: '마리나 베이 샌즈, 가든스 바이 더 베이 등 싱가포르의 아이콘이 모인 지역.',
        walkable: true,
        timeNeeded: '반나절',
        places: [
          {
            name: '마리나 베이 샌즈 스카이파크',
            nameLocal: 'Marina Bay Sands SkyPark',
            category: '관광지',
            description: '싱가포르의 상징. 57층 옥상 전망대에서 도시 전경 감상.',
            mustVisit: true,
            hours: '11:00~21:00',
            admission: '26 SGD',
            duration: '1시간',
            latitude: 1.2834,
            longitude: 103.8607,
            rating: 4.5,
          },
          {
            name: '가든스 바이 더 베이',
            nameLocal: 'Gardens by the Bay',
            category: '공원',
            description: '거대한 인공 나무 슈퍼트리 그로브와 클라우드 포레스트, 플라워 돔.',
            mustVisit: true,
            hours: '05:00~02:00 (야외) / 09:00~21:00 (돔)',
            admission: '야외 무료 / 돔 32 SGD',
            duration: '2~3시간',
            latitude: 1.2816,
            longitude: 103.8636,
            rating: 4.7,
            tips: '19:45·20:45 슈퍼트리 라이트쇼(무료) 꼭 보세요.',
          },
        ],
      },
      {
        name: '차이나타운·리틀 인디아',
        nameLocal: 'Chinatown & Little India',
        description: '다문화 싱가포르의 진면목. 중국·인도·말레이 문화가 공존.',
        walkable: true,
        timeNeeded: '3~4시간',
        places: [
          {
            name: '차이나타운',
            nameLocal: 'Chinatown',
            category: '관광지',
            description: '호커 센터, 사원, 기념품 가게가 밀집한 활기찬 거리.',
            mustVisit: true,
            hours: '상시',
            duration: '2시간',
            latitude: 1.2833,
            longitude: 103.8434,
            rating: 4.3,
          },
          {
            name: '리틀 인디아',
            nameLocal: 'Little India',
            category: '관광지',
            description: '화려한 색감의 힌두 사원과 향신료 냄새가 가득한 인도 문화 거리.',
            mustVisit: false,
            hours: '상시',
            duration: '1.5시간',
            latitude: 1.3066,
            longitude: 103.8518,
            rating: 4.2,
          },
        ],
      },
      {
        name: '센토사 섬',
        nameLocal: 'Sentosa Island',
        description: '유니버설 스튜디오, 해변, 어드벤처 시설이 모인 엔터테인먼트 섬.',
        walkable: true,
        timeNeeded: '1일',
        places: [
          {
            name: '유니버설 스튜디오 싱가포르',
            nameLocal: 'Universal Studios Singapore',
            category: '체험',
            description: '동남아 유일의 유니버설 스튜디오. 24개 어트랙션.',
            mustVisit: true,
            hours: '10:00~19:00',
            admission: '81 SGD',
            duration: '6~8시간',
            latitude: 1.2540,
            longitude: 103.8238,
            rating: 4.5,
          },
        ],
      },
    ],
    foods: [
      { name: '칠리 크랩', nameLocal: 'Chilli Crab', description: '달콤·매콤한 소스에 볶은 통게. 싱가포르 국민 음식.', priceRange: '40~80 SGD', mustTry: true, bestSpots: ['점보 씨푸드', '노 사이닝 보드'], mealType: 'dinner' },
      { name: '하이난 치킨라이스', nameLocal: 'Hainanese Chicken Rice', description: '부드러운 닭고기에 치킨 스톡으로 지은 밥. 심플하지만 완벽한 조합.', priceRange: '4~6 SGD', mustTry: true, bestSpots: ['티안티안', '웡아킨'], mealType: 'lunch' },
      { name: '락사', nameLocal: 'Laksa', description: '코코넛 밀크 커리 수프에 쌀국수를 넣은 페라나칸 요리.', priceRange: '5~8 SGD', mustTry: true, bestSpots: ['328 카통 락사', '싼 도우'], mealType: 'lunch' },
      { name: '카야 토스트', nameLocal: 'Kaya Toast', description: '코코넛 잼(카야)과 버터를 바른 토스트. 반숙 계란과 커피가 세트.', priceRange: '4~6 SGD', mustTry: true, bestSpots: ['야쿤 카야 토스트', '킬리니 코피티암'], mealType: 'breakfast' },
    ],
    events: [
      { name: '싱가포르 그랑프리', nameLocal: 'Singapore Grand Prix', period: '9~10월', description: '세계 유일의 시가지 야간 F1 레이스.', highlight: '마리나 베이를 질주하는 F1 머신과 도시 야경의 조합' },
      { name: '중국 설날', nameLocal: 'Chinese New Year', period: '1~2월', description: '차이나타운을 중심으로 화려한 장식과 사자춤 퍼레이드.', highlight: '리버 홍바오 축제와 칭게이 퍼레이드' },
    ],
    transportLinks: [
      { from: '인천', method: '직항', duration: '약 6시간 30분', cost: '250,000~600,000원' },
      { from: '창이 공항→시내', method: 'MRT', duration: '약 30분', cost: '2 SGD' },
    ],
    neighborCities: [
      { cityId: 'johor', cityName: '조호르바루 (말레이시아)', transport: '버스', duration: '약 1시간', dayTripViable: true },
      { cityId: 'batam', cityName: '바탐 섬 (인도네시아)', transport: '페리', duration: '약 1시간', dayTripViable: true },
    ],
    travelTips: [
      'MRT(지하철)·버스로 거의 모든 곳 이동 가능. 이지링크 카드 구매 추천',
      '호커 센터에서 3~5 SGD로 한 끼 해결 가능 (미쉐린 맛집도 호커에)',
      '껌 반입 금지, 쓰레기 무단 투기 벌금 등 법규가 엄격',
      '실내 에어컨이 매우 강하니 얇은 겉옷 필수',
      '영어가 공용어라 의사소통 편리',
    ],
    tags: ['미식', '깨끗한', '다문화', '쇼핑', '야경', '호커센터', '가든'],
  },
];
