import { CityProfile } from './types';

// ─── Americas City Data ─────────────────────────────────

export const US_CITIES: CityProfile[] = [
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // NEW YORK (纽约)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'newyork',
    name: '뉴욕',
    nameLocal: 'New York',
    country: '미국',
    region: '북미',
    description: '세계 문화·경제의 중심지. 브로드웨이, 센트럴파크, 자유의 여신상이 있는 꿈의 도시.',
    character: '잠들지 않는 세계의 수도',
    bestSeasons: ['spring', 'autumn'],
    averageStay: '4~6일',
    budgetPerDay: { economy: '150,000~250,000원', mid: '300,000~500,000원', premium: '700,000원~' },
    areas: [
      {
        name: '맨해튼 미드타운',
        nameLocal: 'Midtown Manhattan',
        description: '타임스 스퀘어, 엠파이어 스테이트 빌딩, 브로드웨이가 모인 뉴욕의 심장.',
        walkable: true,
        timeNeeded: '1일',
        places: [
          {
            name: '타임스 스퀘어',
            nameLocal: 'Times Square',
            category: '관광지',
            description: '네온사인이 빛나는 세계에서 가장 유명한 광장. 브로드웨이 극장가 중심.',
            mustVisit: true,
            hours: '상시',
            duration: '1시간',
            latitude: 40.7580,
            longitude: -73.9855,
            rating: 4.3,
          },
          {
            name: '엠파이어 스테이트 빌딩',
            nameLocal: 'Empire State Building',
            category: '관광지',
            description: '86층 전망대에서 맨해튼 360도 파노라마 감상.',
            mustVisit: true,
            hours: '10:00~00:00',
            admission: '$42',
            duration: '1~2시간',
            latitude: 40.7484,
            longitude: -73.9857,
            rating: 4.6,
            tips: '일몰 30분 전 입장이 최고의 타이밍.',
          },
          {
            name: '톱 오브 더 록',
            nameLocal: 'Top of the Rock',
            category: '관광지',
            description: '록펠러 센터 전망대. 센트럴파크와 엠파이어 스테이트 빌딩 동시 감상.',
            mustVisit: true,
            hours: '09:00~00:00',
            admission: '$40',
            duration: '1시간',
            latitude: 40.7593,
            longitude: -73.9794,
            rating: 4.7,
          },
        ],
      },
      {
        name: '센트럴파크·어퍼 웨스트',
        nameLocal: 'Central Park & Upper West Side',
        description: '맨해튼의 허파. 메트로폴리탄 미술관과 자연사 박물관 인접.',
        walkable: true,
        timeNeeded: '반나절',
        places: [
          {
            name: '센트럴파크',
            nameLocal: 'Central Park',
            category: '공원',
            description: '3.4km² 규모의 도시 공원. 산책, 보트, 피크닉의 뉴요커 일상.',
            mustVisit: true,
            hours: '06:00~01:00',
            duration: '2~3시간',
            latitude: 40.7829,
            longitude: -73.9654,
            rating: 4.8,
          },
          {
            name: '메트로폴리탄 미술관',
            nameLocal: 'The Metropolitan Museum of Art',
            category: '관광지',
            description: '세계 3대 미술관. 이집트 신전부터 현대미술까지 200만 점 소장.',
            mustVisit: true,
            hours: '10:00~17:00 (금토 ~21:00)',
            admission: '$30 (추천 기부제)',
            duration: '3~4시간',
            latitude: 40.7794,
            longitude: -73.9632,
            rating: 4.8,
          },
        ],
      },
      {
        name: '로어 맨해튼·브루클린',
        nameLocal: 'Lower Manhattan & Brooklyn',
        description: '자유의 여신상, 월스트리트, 브루클린 브릿지 등 아이코닉 명소.',
        walkable: true,
        timeNeeded: '반나절',
        places: [
          {
            name: '자유의 여신상',
            nameLocal: 'Statue of Liberty',
            category: '관광지',
            description: '뉴욕과 미국의 상징. 페리를 타고 리버티 섬으로.',
            mustVisit: true,
            hours: '09:00~17:00',
            admission: '$24 (페리 포함)',
            duration: '3~4시간',
            latitude: 40.6892,
            longitude: -74.0445,
            rating: 4.6,
            tips: '왕관 입장은 수개월 전 예약 필요. 일반 페리만으로도 충분히 감상 가능.',
          },
          {
            name: '브루클린 브릿지',
            nameLocal: 'Brooklyn Bridge',
            category: '관광지',
            description: '1883년 완공된 아이코닉한 현수교. 도보로 건너며 맨해튼 스카이라인 감상.',
            mustVisit: true,
            hours: '상시',
            duration: '1시간',
            latitude: 40.7061,
            longitude: -73.9969,
            rating: 4.7,
          },
        ],
      },
    ],
    foods: [
      { name: '뉴욕 피자', nameLocal: 'New York-Style Pizza', description: '크고 얇은 크러스트에 접어서 먹는 뉴욕 스타일 피자.', priceRange: '$1~5 (슬라이스)', mustTry: true, bestSpots: ['조스 피자', '디파라 피자', '프린스 스트리트 피자'], mealType: 'any' },
      { name: '베이글', nameLocal: 'Bagel', description: '크림치즈, 훈제 연어를 얹은 뉴욕식 베이글.', priceRange: '$3~10', mustTry: true, bestSpots: ['러스 & 도터스', '에사 베이글'], mealType: 'breakfast' },
      { name: '파스트라미 샌드위치', nameLocal: 'Pastrami Sandwich', description: '두껍게 쌓은 훈제 파스트라미 비프 샌드위치.', priceRange: '$15~25', mustTry: true, bestSpots: ['카츠 델리카트슨'], mealType: 'lunch' },
      { name: '치즈케이크', nameLocal: 'New York Cheesecake', description: '크리미하고 진한 뉴욕 스타일 치즈케이크.', priceRange: '$8~12', mustTry: false, bestSpots: ['주니어스', '레이디 M'], mealType: 'snack' },
    ],
    events: [
      { name: '뉴욕 새해 카운트다운', nameLocal: 'New Year\'s Eve Ball Drop', period: '12월 31일', description: '타임스 스퀘어에서 전 세계가 함께하는 새해 카운트다운.', highlight: '볼 드롭 순간 100만 명이 함께하는 카운트다운' },
      { name: '메이시스 추수감사절 퍼레이드', nameLocal: 'Macy\'s Thanksgiving Day Parade', period: '11월 넷째 목요일', description: '거대 캐릭터 풍선이 맨해튼을 행진하는 전통 퍼레이드.', highlight: '거대한 풍선과 브로드웨이 공연' },
    ],
    transportLinks: [
      { from: '인천', method: '직항', duration: '약 14시간', cost: '800,000~1,500,000원' },
      { from: 'JFK 공항→맨해튼', method: '에어트레인+지하철', duration: '약 1시간', cost: '$10.75' },
    ],
    neighborCities: [
      { cityId: 'washington', cityName: '워싱턴 D.C.', transport: 'Amtrak', duration: '약 3시간', dayTripViable: false },
      { cityId: 'boston', cityName: '보스턴', transport: 'Amtrak', duration: '약 3시간 30분', dayTripViable: false },
    ],
    travelTips: [
      '메트로카드(지하철 무제한 7일권 $33) 구매 추천',
      '브로드웨이 티켓은 TKTS 부스에서 당일 할인 구매 가능',
      '팁 문화: 레스토랑 18~20%, 택시 15~20%, 바리스타 $1~2',
      '맨해튼 내 이동은 지하철이 택시보다 빠른 경우가 많음',
      '무료 명소: 센트럴파크, 하이라인, 페리(스태튼 아일랜드), 9/11 메모리얼',
    ],
    tags: ['대도시', '미술관', '브로드웨이', '미식', '쇼핑', '야경', '자유의여신상'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // HAWAII / HONOLULU
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'hawaii',
    name: '하와이',
    nameLocal: 'Hawaiʻi (Honolulu)',
    country: '미국',
    region: '북미 (태평양)',
    description: '와이키키 해변, 다이아몬드 헤드, 알로하 정신이 살아 숨 쉬는 태평양의 낙원.',
    character: '알로하 정신이 살아있는 열대 파라다이스',
    bestSeasons: ['spring', 'autumn', 'winter'],
    averageStay: '5~7일',
    budgetPerDay: { economy: '150,000~250,000원', mid: '300,000~500,000원', premium: '600,000원~' },
    areas: [
      {
        name: '와이키키',
        nameLocal: 'Waikiki',
        description: '호놀룰루의 관광 중심지. 해변, 쇼핑, 레스토랑이 밀집.',
        walkable: true,
        timeNeeded: '1~2일',
        places: [
          {
            name: '와이키키 비치',
            nameLocal: 'Waikiki Beach',
            category: '비치',
            description: '세계에서 가장 유명한 해변 중 하나. 서핑, 수영, 선탠의 메카.',
            mustVisit: true,
            hours: '상시',
            duration: '반나절',
            latitude: 21.2769,
            longitude: -157.8268,
            rating: 4.5,
          },
          {
            name: '다이아몬드 헤드',
            nameLocal: 'Diamond Head',
            category: '자연',
            description: '분화구 정상까지 약 40분 하이킹. 와이키키와 태평양 절경 감상.',
            mustVisit: true,
            hours: '06:00~18:00',
            admission: '$5 (도보)',
            duration: '2시간',
            latitude: 21.2624,
            longitude: -157.8056,
            rating: 4.6,
            tips: '사전 예약 필수. 오전 일찍 가면 덜 더워요.',
          },
        ],
      },
      {
        name: '노스 쇼어',
        nameLocal: 'North Shore',
        description: '서핑의 성지. 겨울엔 대형 파도, 여름엔 스노클링 천국.',
        walkable: false,
        timeNeeded: '1일',
        places: [
          {
            name: '할레이와 타운',
            nameLocal: 'Haleiwa Town',
            category: '쇼핑',
            description: '서퍼 문화가 살아있는 아기자기한 타운. 새우 트럭이 유명.',
            mustVisit: true,
            hours: '상시',
            duration: '2~3시간',
            latitude: 21.5934,
            longitude: -158.1026,
            rating: 4.4,
          },
          {
            name: '선셋 비치',
            nameLocal: 'Sunset Beach',
            category: '비치',
            description: '노스 쇼어 대표 해변. 겨울엔 세계 서핑 대회가 열림.',
            mustVisit: true,
            hours: '상시',
            duration: '2~3시간',
            latitude: 21.6749,
            longitude: -158.0404,
            rating: 4.6,
          },
        ],
      },
      {
        name: '다운타운 호놀룰루·펄하버',
        nameLocal: 'Downtown Honolulu & Pearl Harbor',
        description: '역사와 문화의 중심지. 이올라니 궁전, 펄하버 기념관.',
        walkable: false,
        timeNeeded: '반나절',
        places: [
          {
            name: '펄하버 국립기념관',
            nameLocal: 'Pearl Harbor National Memorial',
            category: '관광지',
            description: 'USS 아리조나 기념관. 2차 세계대전 역사의 현장.',
            mustVisit: true,
            hours: '07:00~17:00',
            admission: '무료 (사전예약 필수)',
            duration: '3시간',
            latitude: 21.3649,
            longitude: -157.9501,
            rating: 4.7,
            tips: '온라인 예약 필수. 큰 가방 반입 불가.',
          },
        ],
      },
    ],
    foods: [
      { name: '포케 (포키)', nameLocal: 'Poke', description: '참치·연어 등 신선한 생선을 양념한 하와이 대표 음식.', priceRange: '$12~20', mustTry: true, bestSpots: ['오노 시푸드', '포케바'], mealType: 'lunch' },
      { name: '로코모코', nameLocal: 'Loco Moco', description: '밥 위에 햄버그 스테이크, 달걀 프라이, 그레이비 소스.', priceRange: '$10~15', mustTry: true, bestSpots: ['레인보우 드라이브인'], mealType: 'lunch' },
      { name: '새우 트럭', nameLocal: 'Shrimp Truck', description: '노스 쇼어 명물. 갈릭 버터 새우가 대표 메뉴.', priceRange: '$13~16', mustTry: true, bestSpots: ['지오반니스', '로미스'], mealType: 'lunch' },
      { name: '아사이 볼', nameLocal: 'Açaí Bowl', description: '아사이 퓨레에 그래놀라·과일을 얹은 건강한 아침 식사.', priceRange: '$10~15', mustTry: false, bestSpots: ['할레이와 보울', '란카이 쥬스'], mealType: 'breakfast' },
    ],
    events: [
      { name: '에디 아이카우 빅웨이브', nameLocal: 'Eddie Aikau Big Wave Invitational', period: '12~2월 (파도 조건 시)', description: '노스 쇼어 웨이메아 베이에서 열리는 전설적 빅웨이브 서핑 대회.', highlight: '20m 이상 파도에서 서핑하는 세계 최고 서퍼들' },
      { name: '알로하 페스티벌', nameLocal: 'Aloha Festivals', period: '9월', description: '하와이 문화를 축하하는 최대 규모 축제.', highlight: '와이키키 거리 퍼레이드와 전통 훌라 공연' },
    ],
    transportLinks: [
      { from: '인천', method: '직항', duration: '약 8시간 30분', cost: '600,000~1,200,000원' },
      { from: '호놀룰루 공항→와이키키', method: '버스/택시', duration: '약 30~45분', cost: '$3(버스) / $40~50(택시)' },
    ],
    neighborCities: [
      { cityId: 'maui', cityName: '마우이', transport: '비행기', duration: '약 30분', dayTripViable: false },
      { cityId: 'bigisland', cityName: '빅아일랜드', transport: '비행기', duration: '약 45분', dayTripViable: false },
    ],
    travelTips: [
      '렌터카가 사실상 필수. 국제운전면허증 준비',
      '자외선이 매우 강하니 SPF50+ 선크림 필수',
      '노스 쇼어는 와이키키에서 차로 약 1시간',
      '팁 문화: 레스토랑 18~20%, 프리미엄 레스토랑은 별도 서비스 차지 확인',
      'ABC 스토어 (편의점)이 와이키키 곳곳에 있어 편리',
    ],
    tags: ['해변', '서핑', '하이킹', '자연', '알로하', '포케', '리조트'],
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // LOS ANGELES
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'losangeles',
    name: 'LA',
    nameLocal: 'Los Angeles',
    country: '미국',
    region: '북미',
    description: '할리우드, 산타모니카, 비벌리힐스. 엔터테인먼트와 해변 문화의 중심지.',
    character: '꿈과 태양의 엔터테인먼트 시티',
    bestSeasons: ['spring', 'autumn'],
    averageStay: '4~6일',
    budgetPerDay: { economy: '120,000~200,000원', mid: '250,000~400,000원', premium: '600,000원~' },
    areas: [
      {
        name: '할리우드',
        nameLocal: 'Hollywood',
        description: '영화의 도시 할리우드. 명예의 거리, 차이니즈 시어터, 할리우드 사인.',
        walkable: true,
        timeNeeded: '반나절',
        places: [
          {
            name: '할리우드 명예의 거리',
            nameLocal: 'Hollywood Walk of Fame',
            category: '관광지',
            description: '2,700개 이상의 스타 이름이 새겨진 거리. 차이니즈 시어터 앞 핸드프린트도.',
            mustVisit: true,
            hours: '상시',
            duration: '1~2시간',
            latitude: 34.1016,
            longitude: -118.3267,
            rating: 4.1,
          },
          {
            name: '그리피스 천문대',
            nameLocal: 'Griffith Observatory',
            category: '관광지',
            description: '할리우드 사인과 LA 시내 전경을 한눈에. 무료 입장.',
            mustVisit: true,
            hours: '12:00~22:00 (주중) / 10:00~22:00 (주말)',
            admission: '무료',
            duration: '1.5~2시간',
            latitude: 34.1184,
            longitude: -118.3004,
            rating: 4.7,
            tips: '선셋 타이밍에 방문하면 야경 전환이 아름다워요.',
          },
        ],
      },
      {
        name: '산타모니카·베니스',
        nameLocal: 'Santa Monica & Venice',
        description: 'LA 대표 해변 지역. 산타모니카 피어와 베니스 비치 보드워크.',
        walkable: true,
        timeNeeded: '반나절',
        places: [
          {
            name: '산타모니카 피어',
            nameLocal: 'Santa Monica Pier',
            category: '관광지',
            description: '루트66의 끝점. 관람차와 해변이 어우러진 아이코닉 명소.',
            mustVisit: true,
            hours: '상시',
            duration: '2시간',
            latitude: 34.0083,
            longitude: -118.4987,
            rating: 4.5,
          },
          {
            name: '베니스 비치',
            nameLocal: 'Venice Beach',
            category: '비치',
            description: '스트리트 퍼포먼스, 머슬 비치, 독특한 예술가 문화의 해변.',
            mustVisit: true,
            hours: '상시',
            duration: '2~3시간',
            latitude: 33.9850,
            longitude: -118.4695,
            rating: 4.3,
          },
        ],
      },
      {
        name: '유니버설·다운타운',
        nameLocal: 'Universal & Downtown LA',
        description: '유니버설 스튜디오와 재개발 중인 다운타운 LA.',
        walkable: false,
        timeNeeded: '1일',
        places: [
          {
            name: '유니버설 스튜디오 할리우드',
            nameLocal: 'Universal Studios Hollywood',
            category: '체험',
            description: '해리포터, 쥬라기 월드 등 인기 어트랙션. 실제 영화 촬영소 투어도 가능.',
            mustVisit: true,
            hours: '09:00~22:00 (시즌별 변동)',
            admission: '$109~',
            duration: '6~8시간',
            latitude: 34.1381,
            longitude: -118.3534,
            rating: 4.5,
          },
        ],
      },
    ],
    foods: [
      { name: '인앤아웃 버거', nameLocal: 'In-N-Out Burger', description: 'LA 발상의 전설적 버거 체인. 시크릿 메뉴 "Animal Style"이 유명.', priceRange: '$5~10', mustTry: true, bestSpots: ['LAX 근처점', '할리우드점'], mealType: 'any' },
      { name: '타코', nameLocal: 'Taco', description: 'LA의 멕시칸 타코는 미국 최고 수준. 길거리 타코 트럭도 일품.', priceRange: '$2~5 (개당)', mustTry: true, bestSpots: ['게레로스', '레오스 타코 트럭'], mealType: 'any' },
      { name: '아사이 볼', nameLocal: 'Açaí Bowl', description: 'LA 건강식 트렌드의 대표. 그래놀라와 과일 토핑.', priceRange: '$12~16', mustTry: false, bestSpots: ['사모바라', '얼쓰바'], mealType: 'breakfast' },
    ],
    events: [
      { name: '아카데미 시상식', nameLocal: 'Academy Awards (Oscars)', period: '2~3월', description: '할리우드의 가장 큰 밤. 돌비 시어터에서 개최.', highlight: '레드카펫 행사 관람 (공개 관람석 추첨)' },
      { name: '코첼라', nameLocal: 'Coachella', period: '4월', description: 'LA 근교 인디오에서 열리는 세계적 음악 페스티벌.', highlight: '유명 아티스트 공연과 인스타그래머블한 아트 설치물' },
    ],
    transportLinks: [
      { from: '인천', method: '직항', duration: '약 11시간', cost: '600,000~1,200,000원' },
      { from: 'LAX 공항→시내', method: 'FlyAway 버스', duration: '약 30~50분', cost: '$9.75' },
    ],
    neighborCities: [
      { cityId: 'lasvegas', cityName: '라스베이거스', transport: '자동차', duration: '약 4시간', dayTripViable: false },
      { cityId: 'sandiego', cityName: '샌디에이고', transport: 'Amtrak', duration: '약 2시간 45분', dayTripViable: true },
    ],
    travelTips: [
      '렌터카가 사실상 필수. LA는 대중교통이 불편한 도시',
      '주차비가 비싸니 주차장 앱(SpotHero) 활용 추천',
      '할리우드·비벌리힐스·산타모니카는 각각 30분~1시간 거리',
      '팁 문화: 레스토랑 18~20%, 발렛파킹 $2~5',
      '야간 다운타운 일부 지역은 치안 주의',
    ],
    tags: ['할리우드', '해변', '테마파크', '미식', '엔터테인먼트', '드라이브'],
  },
];
